require('dotenv').config();
const mongoose = require('mongoose');
const Day = require('../models/Day');

const updates = [
  {
    dayNumber: 31,
    title: 'Business English',
    description: 'Day 31: The second half begins! Business English is the language of opportunity. It gets you hired, earns you respect in meetings, and helps you communicate with clients and colleagues professionally. Today every word you learn has direct career value.',
    tasks: [
      { type: 'speaking', title: 'Pitch Yourself in 2 Minutes', description: 'Speak for 2 minutes as if you are in a business meeting introducing yourself to a new client or employer. Cover: your name and role, your key skill or value, one achievement you are proud of, and what you can offer. Use professional phrases: "I specialize in...", "My strength lies in...", "I have successfully...", "What I bring to the table is..." This is called an elevator pitch - practice it until it feels natural.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Business English Meeting Conversations', description: 'Search YouTube for "business English meeting conversation" and watch a 5-minute video. Write down: 3 phrases used to agree professionally ("That is a great point", "I completely agree", "Absolutely"), 2 phrases to politely disagree ("I see your point, however...", "With respect, I think..."), and 1 phrase to close a discussion. These phrases make you sound confident in any meeting.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Business Email Aloud', description: 'Read slowly and professionally: "Subject: Partnership Proposal - Every Day Better Platform. Dear Ms. Kapoor, I hope this email finds you well. I am writing on behalf of our team at EDB Solutions to explore a potential partnership between our organizations. Having reviewed your company\'s impressive growth over the past year, I believe there is a significant opportunity for mutual benefit. I would welcome the chance to schedule a brief call at your convenience to discuss this further. Please find our company profile attached for your reference. I look forward to hearing from you. Warm regards, Arjun Mehta, Business Development Manager." Read it twice with full professional focus.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Business English - 10 Power Words', description: 'Learn: Synergy ("The merger created great synergy between both teams"), Leverage ("We can leverage our existing client relationships"), Scalable ("This is a scalable business model"), ROI ("The marketing campaign delivered excellent ROI"), Stakeholder ("All stakeholders must approve this decision"), Benchmark ("We need to benchmark against industry standards"), Streamline ("Let us streamline the approval process"), Fiscal ("The fiscal year ends in March"), Viable ("Is this a financially viable option?"), Acquisition ("The company completed its largest acquisition last week"). Write each in a business sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Formal Sentence Structures for Business', description: 'Business English uses specific formal patterns. Learn these and write 2 sentences using each: 1) "I would like to + verb": "I would like to discuss the budget." 2) "Could you please + verb": "Could you please send the report by Friday?" 3) "I am writing to + verb": "I am writing to confirm our meeting." 4) "Please find attached": "Please find attached the revised proposal." 5) "I look forward to + gerund": "I look forward to hearing from you." Now write your own business email using at least 4 of these structures.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Record Your Perfect Elevator Pitch', description: 'Record a polished 60-second professional introduction. Imagine you are walking into your dream company for an interview. Start strong, speak clearly, end confidently. After recording, listen back critically: Did you sound confident? Did you speak too fast? Was your vocabulary professional? Record it again until you are genuinely proud of it.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 32,
    title: 'Interview Skills',
    description: 'Day 32: This is one of the most important days in the entire 60-day journey. Interview English can change your life - literally. The difference between getting a job and not getting it is often just how confidently and clearly you speak English. Today we practice hard.',
    tasks: [
      { type: 'speaking', title: 'Answer 3 Common Interview Questions', description: 'Speak answers to these 3 questions - take 30-40 seconds each: 1) "Tell me about yourself." 2) "What is your greatest strength?" 3) "Where do you see yourself in 5 years?" For each answer use the STAR method where possible: Situation, Task, Action, Result. Avoid: "I am a hardworking person" - everyone says this. Be specific with real examples from your life.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Mock Job Interview in English', description: 'Search YouTube for "mock job interview English India" or "HR interview English answers" and watch one full mock interview. Write down: 3 answers that impressed you and why, 2 phrases you want to use in your own interview, and 1 thing the candidate did well with body language or tone.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read These Model Interview Answers Aloud', description: 'Read clearly and confidently: "Tell me about yourself: I am a motivated engineering graduate from Pune with a strong interest in data analysis. Over the past year I have completed two online certifications and built three personal projects that I can share with you today. I am passionate about solving real problems with data and I am excited about the opportunity to contribute to your team. My greatest weakness: I tend to take on too much at once because I am genuinely enthusiastic about every new challenge. I have been working on this by prioritizing tasks using a daily planner and it has made a significant difference." Read each answer twice.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Interview Vocabulary - 10 Words', description: 'Learn: Proactive ("I am a proactive team member who takes initiative"), Adaptable ("I am adaptable and learn new tools quickly"), Meticulous ("She is meticulous with financial data"), Collaborative ("I thrive in collaborative environments"), Resilient ("You need to be resilient in a fast-paced startup"), Articulate ("He is very articulate in client meetings"), Competency ("Strong communication is a core competency for this role"), Integrity ("We only hire people with absolute integrity"), Track record ("She has an impressive track record in sales"), Aspiration ("My long-term aspiration is to lead a product team"). Write each in an interview context sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Past Perfect for Interview Stories - I Had Done', description: 'Interviews require talking about past experience using past perfect: "By the time I graduated, I had already completed two internships." "I had never led a team before, but I had always wanted the opportunity." "After I had finished the project, I realized I had learned more in 3 months than in 3 years." Pattern: had + past participle. Write 4 sentences about your own experience or education using past perfect. This tense makes your English sound advanced and impressive to interviewers.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Full 2-Minute Mock Interview Recording', description: 'Record yourself answering this interview question as if your dream job depends on it: "Tell me about a challenge you faced and how you overcame it." Use the STAR method: describe the Situation, the Task you faced, the Actions you took, and the Result you achieved. Speak for a full 2 minutes. Listen back and ask: Would I hire this person? If not - what needs to improve?', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 33,
    title: 'Email Writing',
    description: 'Day 33: Every professional sends dozens of emails every week. A well-written email can open doors. A poorly written one can close them. Today you will learn the structure, language, and tone of professional emails that get results.',
    tasks: [
      { type: 'speaking', title: 'Explain the Purpose of a Professional Email', description: 'Speak for 2 minutes answering: Why are emails important in professional life? What makes a good email different from a bad one? Have you ever sent or received an email that impressed you - what made it good? Have you ever received a confusing or rude email - what was wrong with it? Use your real experience to make this conversation genuine.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: How to Write Professional Emails in English', description: 'Search YouTube for "how to write professional email in English" and watch one video. Write down: the 5 parts of a professional email (subject, greeting, body, closing, signature), 3 formal opening phrases, and 3 formal closing phrases. Pay special attention to subject lines - a good subject line determines if your email gets read.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read These Two Emails Aloud - Spot the Difference', description: 'Read both aloud: UNPROFESSIONAL: "hi need the report asap pls send today thanks" PROFESSIONAL: "Subject: Report Submission Request - Urgent. Dear Rahul, I hope you are having a productive day. I am writing to kindly request the monthly sales report at your earliest convenience. As the management review is scheduled for tomorrow morning, it would be greatly appreciated if you could send it by 5 PM today. Please do not hesitate to contact me if you need any assistance. Thank you sincerely, Anjali." Read the professional version twice - notice every element that makes it effective.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Email Vocabulary - 10 Words', description: 'Learn: Acknowledge ("I am writing to acknowledge receipt of your email"), Clarify ("Could you please clarify the deadline?"), Expedite ("We need to expedite this approval process"), Tentative ("I have a tentative meeting at 3 PM - can we reschedule?"), Reiterate ("I would like to reiterate our commitment to quality"), Pursuant ("Pursuant to our last discussion, I have prepared the report"), Concise ("Please keep your email concise and to the point"), Cordial ("Always maintain a cordial tone in professional emails"), Attachment ("Please review the attachment and share your feedback"), Grievance ("Please submit your grievance through the official channel"). Write each in an email context.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Polite Request Structures in Emails', description: 'Emails use specific grammar to sound polite, not demanding. Practice these patterns - write 2 sentences each: 1) Could you please + verb: "Could you please confirm attendance?" 2) I would appreciate it if + past tense: "I would appreciate it if you could send the file." 3) Would it be possible to + verb: "Would it be possible to reschedule?" 4) I was wondering if + past tense: "I was wondering if you could help." 5) Please do not hesitate to: "Please do not hesitate to contact me." Now write a complete 5-sentence professional email using these structures.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Write and Read Your Own Professional Email', description: 'Write a real professional email - could be to a college, a company for an internship inquiry, or a formal request to anyone. Then record yourself reading it aloud clearly. After listening back, ask: Does it sound professional? Is the tone right? Is it clear and concise? Rewrite any part that does not sound right and record again.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 34,
    title: 'Phone Conversations',
    description: 'Day 34: Many people who speak reasonable English completely freeze on the phone - because you cannot see the other person\'s face or body language. Phone English has its own unique phrases and structure. Today you will master them.',
    tasks: [
      { type: 'speaking', title: 'Practice a Professional Phone Call Opening', description: 'Speak for 2 minutes practicing these phone scenarios back to back: 1) Calling a company: "Good morning, this is Priya calling from ABC Solutions. Could I speak with Mr. Sharma please?" 2) Receiving a call professionally: "Good afternoon, EDB Technologies, Rohan speaking. How may I help you?" 3) Leaving a voicemail: "Hi, this is Ankit. I am calling regarding the project proposal we discussed. Could you please call me back at your earliest convenience? My number is..." Practice until all three feel completely natural.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Professional Phone Call Examples in English', description: 'Search YouTube for "professional phone call English examples" or "customer service English phone call" and watch one video. Write down: How do they greet the caller? How do they ask someone to hold? How do they transfer a call? How do they end the call professionally? Phone etiquette in English follows specific patterns - learn them today.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Phone Conversation Script Aloud', description: 'Read both roles clearly: "Receptionist: Good morning, Sunrise Hospital, how may I direct your call? Caller: Good morning. I would like to speak with Dr. Mehta\'s office regarding an appointment please. Receptionist: Of course. May I have your name please? Caller: Yes, it is Kavya Sharma. Receptionist: Thank you, Ms. Sharma. I am connecting you now. Please hold for just a moment. Caller: Thank you. [pause] Dr. Mehta\'s Assistant: Good morning, Dr. Mehta\'s office. How can I help you? Caller: Hello, I would like to book an appointment for next Tuesday if possible." Read it twice - switch roles the second time.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Phone Conversation - 10 Essential Phrases', description: 'Learn these as complete phrases, not single words: "I am afraid he is not available" (polite way to say someone is busy), "Could I take a message?" (offer to write down information), "I will put you through" (I will connect you), "Could you speak up please?" (I cannot hear you clearly), "I am sorry, we got cut off" (the call disconnected), "Let me just pull up your details" (I am checking your information), "Is there anything else I can help you with?" (are you finished?), "I will make sure he gets your message" (I will tell him), "Could I have your callback number?" (what is your phone number?), "Thank you for calling" (end of call). Practice saying each phrase naturally.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Indirect Questions - Polite Phone Grammar', description: 'Direct questions sound rude on the phone. Indirect questions sound professional. Direct: "What is your name?" Indirect: "Could I ask who is calling?" Direct: "Why are you calling?" Indirect: "Could I ask what this is regarding?" Direct: "When did you call before?" Indirect: "Could you tell me when you last called?" Pattern: Could I ask + question word + subject + verb. Convert these to indirect questions: 1) "What do you want?" 2) "Who told you about us?" 3) "When is the meeting?" Write 4 of your own indirect question transformations.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Roleplay a Customer Support Call', description: 'Record yourself handling a full customer support call for 1 minute. Play both roles - the customer with a complaint and the support agent resolving it. Customer: "I ordered a product 2 weeks ago and it has not arrived." Agent: handle it professionally. Use: "I completely understand your frustration...", "Let me check that for you right away...", "I sincerely apologize for the inconvenience..." This is exactly the scenario in BPO and customer service interviews.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 35,
    title: 'Presentations',
    description: 'Day 35: More than halfway there! Giving a presentation in English is one of the most valued skills in any career. Whether it is a college seminar, a work meeting, or a community talk - today you will learn how to open strongly, speak clearly, and end memorably.',
    tasks: [
      { type: 'speaking', title: 'Give a 2-Minute Mini Presentation', description: 'Choose any topic you know well - your hobby, your city, a skill you have, or why learning English matters. Structure your 2 minutes like this: Opening hook (15 sec) + Main point 1 with example (30 sec) + Main point 2 with example (30 sec) + Main point 3 with example (30 sec) + Strong closing (15 sec). Do not just speak randomly - structure makes the difference between a good speaker and a great one.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: A Short TED Talk or Presentation', description: 'Search YouTube for "TED talk 5 minutes English" and watch one. Notice: How do they open? (story, question, or shocking fact) How do they transition between points? ("Moving on to...", "Another key point is...", "This brings me to...") How do they close? (call to action, powerful quote, circle back to opening). Write down the opening sentence and the closing sentence - these are the most important parts.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Presentation Script Aloud', description: 'Read with energy and pauses: "Good morning everyone. Let me ask you a question - when was the last time you spoke English and felt completely confident? [pause] For most of us, that moment is rare. But it does not have to be. Today I want to share three simple habits that transformed my English in just 60 days. First - speak every single day, even if only to yourself. Second - listen to English for at least 20 minutes daily, whether news, songs, or podcasts. Third - record yourself and listen back without fear. These three habits cost nothing. They require only courage. And they work. Thank you." Read it twice - add hand gestures the second time.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Presentation Language - 10 Phrases', description: 'Learn as complete phrases: "Today I am going to talk about" (opening), "Let me begin by" (starting the first point), "Moving on to my next point" (transition), "What this means is" (explanation), "For example" (giving evidence), "As you can see from this" (referring to a visual), "To summarize" (before conclusion), "In conclusion" (starting the end), "I would like to leave you with" (powerful closing thought), "Are there any questions?" (ending). Write a 6-sentence mini presentation using at least 6 of these phrases.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Signposting Language - Connecting Your Presentation', description: 'Signposting means telling your audience where you are in the presentation. These are transitions that keep listeners engaged: To add: "Furthermore...", "In addition to this...", "Not only that, but..." To contrast: "However...", "On the other hand...", "Despite this..." To give examples: "For instance...", "A perfect example of this is...", "To illustrate..." To conclude: "Therefore...", "As a result...", "This shows us that..." Write a short paragraph about any topic using at least 5 different signposting words. Your speech should flow like a river, not jump like a frog.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Record and Review Your Full Presentation', description: 'Record yourself giving a complete 1-minute structured presentation on this topic: "Why every Indian student should learn English." Use a strong opening, 2-3 clear points with examples, and a memorable closing. After recording, watch it back and rate yourself on: clarity (1-10), confidence (1-10), structure (1-10). Then record it one more time trying to improve each score.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 36,
    title: 'Debate & Discussion',
    description: 'Day 36: The ability to express and defend your opinion in English is what separates good speakers from great ones. Group discussions and debates are used in campus placements, MBA admissions, and leadership roles. Today you will learn to think and speak at the same time.',
    tasks: [
      { type: 'speaking', title: 'Express Your Opinion on Social Media', description: 'Speak for 2 minutes giving your genuine opinion on this topic: "Is social media more harmful than helpful for young people?" Take a clear position - agree or disagree - and give 3 reasons with examples from real life. Use: "I firmly believe that...", "The evidence clearly shows...", "Consider for example...", "Critics might argue... but I would counter that..." Having an opinion and defending it is the core skill of this day.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: A Simple English Debate', description: 'Search YouTube for "simple English debate for students" or "group discussion tips English" and watch one video. Write: 3 phrases used to agree ("I completely agree with that point"), 3 phrases to politely disagree ("I respect your view, however I think..."), and 2 phrases to add to someone\'s point ("Building on what was said..."). These exact phrases are tested in GD rounds at top companies.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Opinion Paragraph Aloud', description: 'Read with conviction: "Technology is not making us lazy - it is making us free. Critics argue that smartphones have reduced our attention spans and made us dependent on machines. But consider what technology has actually given us: a farmer in rural Bihar can now access weather forecasts on his phone. A girl in a small town can learn from the world\'s best teachers on YouTube for free. A small business owner can reach customers across the country with a single Instagram post. Technology did not create laziness. It revealed it in those who already had it. For those who use it with purpose, technology is the greatest equalizer in human history." Read it twice with full confidence.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Debate & Discussion - 10 Phrases', description: 'Learn as complete usable phrases: "I would like to point out that" (introducing a fact), "The data clearly suggests" (using evidence), "While I acknowledge that" (conceding a point before disagreeing), "However, the counterargument is" (opposing view), "This is a critical issue because" (showing importance), "From my perspective" (personal opinion), "Research has consistently shown" (citing evidence), "I would like to challenge that view" (polite disagreement), "To play devil\'s advocate" (arguing the opposite side), "The crux of the issue is" (the main point). Write 5 sentences using 5 of these phrases about any topic.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Opinion Sentence Starters - Weak vs Strong', description: 'WEAK opinion starters make you sound unsure: "I think maybe...", "Perhaps it could be...", "I am not sure but maybe..." STRONG opinion starters make you sound credible: "I strongly believe that...", "The evidence clearly indicates...", "It is undeniable that...", "Any objective analysis would show...", "History has consistently demonstrated..." Rewrite these weak sentences to make them strong: 1) "I think maybe online learning is okay." 2) "Perhaps technology could be bad sometimes." 3) "I am not sure but maybe we should care about the environment." Write 3 more strong opinion sentences of your own on any debate topic.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Debate Both Sides', description: 'Record yourself arguing BOTH sides of this topic: "Should school uniforms be mandatory?" First 30 seconds: argue FOR uniforms passionately. Then 30 seconds: argue AGAINST uniforms equally passionately. This exercise forces you to think quickly, use debate vocabulary, and speak fluently under pressure - exactly what group discussions require.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 37,
    title: 'Storytelling',
    description: 'Day 37: The best communicators in the world are storytellers. Facts inform, but stories move people. Today you will learn how to turn your real experiences into engaging English stories that capture attention and build deep connections.',
    tasks: [
      { type: 'speaking', title: 'Tell a Story From Your Childhood', description: 'Speak for 2 minutes telling a real childhood memory as a story. Use storytelling language: "It was a hot summer afternoon when...", "I remember exactly how I felt when...", "What happened next surprised everyone...", "Looking back now, I realize that..." A great story has: a setting, a character (you), a problem or moment of tension, and a resolution or lesson. Make us see it, feel it, and remember it.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Storytelling in English', description: 'Search YouTube for "storytelling in English example" or watch any personal story on TED. Notice the storyteller\'s technique: How do they create suspense? How do they use pauses for effect? How do they describe emotions rather than just naming them? Write down 3 storytelling techniques you observed and want to use yourself.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Story Aloud With Full Emotion', description: 'Read slowly, with pauses and feeling: "I was eleven years old when I gave my first English speech. My teacher had selected me without asking - I found out on a Monday that I was speaking in front of 500 students on Friday. I could not sleep. I practiced in the bathroom mirror every night, my voice shaking, my stomach full of butterflies. Friday came. I walked to the microphone, looked out at the sea of faces - and my mind went completely blank. Silence. Five horrifying seconds of silence. Then something happened. I took one deep breath... and started. I do not remember what I said. But I remember finishing. And I remember the clapping. That day, I learned that courage is not the absence of fear. It is speaking anyway." Read it twice - feel every emotion.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Storytelling Words - 10 Essential Words', description: 'Learn: Vivid ("She painted a vivid picture of her village childhood"), Gripping ("The story was so gripping I forgot to eat"), Suspense ("He built suspense perfectly before the big reveal"), Narrate ("She narrated the entire incident calmly"), Protagonist ("The protagonist faces three impossible challenges"), Climax ("The climax of the story left everyone speechless"), Anecdote ("He began his speech with a funny anecdote"), Compelling ("Her personal story was deeply compelling"), Flashback ("The story uses a flashback to explain the mystery"), Moral ("Every good story has a moral worth remembering"). Write each in a sentence about a real story or movie.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Past Continuous + Simple Past for Storytelling', description: 'The most powerful storytelling grammar combines two tenses: Past continuous sets the scene (ongoing background action): "I was walking home from school..." Simple past shows the sudden event: "...when a dog suddenly jumped in front of me." More examples: "We were having dinner when the electricity went off." "She was reading quietly when the phone rang with terrible news." "I was about to give up when everything changed." Write 5 story sentences using this pattern. Each one should feel like the beginning of an interesting story.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Tell Your Most Embarrassing Story', description: 'Record yourself for 1 minute telling your most embarrassing memory in English. The best stories are the ones where something went wrong. Use all your storytelling skills: set the scene, build the tension, describe the embarrassing moment in detail, and end with what you learned or how you laugh about it now. Being able to laugh at yourself in English is a sign of true fluency and confidence.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 38,
    title: 'Idioms & Phrases',
    description: 'Day 38: Idioms are what make English come alive. When you understand and use idioms naturally, you sound like a real English speaker - not someone translating from another language in their head. Today you will learn 10 idioms that Indians can use every single day.',
    tasks: [
      { type: 'speaking', title: 'Use 5 Idioms in a 2-Minute Story', description: 'Create a 2-minute story using at least 5 idioms naturally. Here are 8 to choose from: "break the ice" (start a conversation), "hit the nail on the head" (say exactly the right thing), "bite off more than you can chew" (take on too much), "burn the midnight oil" (work very late), "cost an arm and a leg" (very expensive), "get cold feet" (become nervous before doing something), "miss the boat" (miss an opportunity), "once in a blue moon" (very rarely). The story can be real or imagined - just make the idioms fit naturally.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Common English Idioms Explained', description: 'Search YouTube for "common English idioms with meaning and examples" and watch a 5-minute video. Write 5 idioms you did not know before with their meanings and example sentences. Pay special attention to HOW native speakers use idioms - they sound natural, not forced. The key is using the right idiom in the right situation.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Idiom-Rich Paragraph Aloud', description: 'Read naturally - these idioms should sound like normal speech: "Learning English is not a piece of cake - it takes real effort. When I first started, I would often bite off more than I could chew by trying to learn 50 words a day. I was burning the midnight oil every night but making little progress. Then my teacher hit the nail on the head when she said: speak more, memorize less. At first I got cold feet every time I had to speak in front of others. But I did not miss the boat - I kept going. Now, once in a blue moon, someone tells me my English is excellent. And every time they do, it costs me nothing - but it means everything." Read it twice until the idioms feel natural.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: '10 More Essential Idioms', description: 'Learn with full context: "Hit the books" ("The exam is tomorrow - time to hit the books"), "Under the weather" ("I am feeling under the weather today - slight fever"), "Bite the bullet" ("I did not want to apologize but I bit the bullet"), "Let the cat out of the bag" ("Who let the cat out of the bag about the surprise party?"), "The ball is in your court" ("I have made my offer - the ball is now in your court"), "Sit on the fence" ("Stop sitting on the fence and give me your real opinion"), "Pull someone\'s leg" ("I am just pulling your leg - it was a joke!"), "Give the benefit of the doubt" ("I gave him the benefit of the doubt even though he was late"), "See eye to eye" ("We do not always see eye to eye but we respect each other"), "At the drop of a hat" ("He would help a friend at the drop of a hat"). Write 5 of these in real-life situations.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Fixed Expressions - Idioms Cannot Be Changed', description: 'Unlike regular grammar, idioms are FIXED - you cannot change the words. WRONG: "She burned the morning oil." RIGHT: "She burned the midnight oil." WRONG: "He bit more than he could swallow." RIGHT: "He bit off more than he could chew." WRONG: "It cost an arm and a foot." RIGHT: "It cost an arm and a leg." This is why learning idioms as complete phrases matters. Now write 5 sentences using idioms correctly. Then write the WRONG version of the same idiom to show you understand why it is wrong.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Casual Conversation Using Idioms Naturally', description: 'Record yourself having an imaginary casual phone conversation with a friend for 1 minute. Use at least 4 idioms naturally in the conversation. The conversation should sound relaxed and real - like you are actually talking to someone. Example topics: catching up after a long time, talking about a difficult exam, discussing a big decision you are facing. If the idiom sounds forced, try a different one.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 39,
    title: 'Phrasal Verbs',
    description: 'Day 39: Phrasal verbs are the biggest secret of natural English. Native speakers use them constantly - "give up", "figure out", "look after" - but textbooks barely teach them. Today you will learn the 10 most useful phrasal verbs and use them in real sentences.',
    tasks: [
      { type: 'speaking', title: 'Use Phrasal Verbs in Your Daily Story', description: 'Speak for 2 minutes describing your day today or yesterday using as many phrasal verbs as possible. Use these: woke up, got up, carried on, figured out, gave up, picked up, ran into, came across, put off, ended up. Example: "I woke up late this morning and almost gave up on my exercise plan. But I carried on anyway..." Make it about YOUR real day - the more personal, the better.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Phrasal Verbs in Natural English', description: 'Search YouTube for "phrasal verbs in natural English conversation" and watch a 5-minute video. Notice how naturally native speakers use them - you will start hearing them everywhere once you know them. Write down 5 phrasal verbs used in the video with their meaning and the sentence they appeared in. Context is everything with phrasal verbs.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Phrasal Verb Story Aloud', description: 'Read naturally: "I came across an old photograph yesterday while I was clearing out my drawer. I picked it up and straight away I broke down - it was a photo of my grandfather. He passed away three years ago. I had been putting off going through his belongings, but I finally decided to get on with it. As I sorted through his things, I came across letters he had written but never sent. I sat down and read every one. By the end I had figured out something important: he had been holding back his feelings his whole life. I made up my mind right then - I would never do the same." Read it twice, noticing how natural the phrasal verbs sound.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: '10 Essential Phrasal Verbs', description: 'Learn with full example sentences: Give up ("Never give up on your dreams - keep going"), Carry on ("Despite the rain, we carried on with the match"), Look after ("Please look after my bag while I use the bathroom"), Turn out ("The exam turned out to be easier than I expected"), Run into ("I ran into my old teacher at the supermarket"), Come up with ("She came up with a brilliant solution"), Put off ("Do not put off until tomorrow what you can do today"), Break down ("The car broke down on the highway"), Get along ("I get along very well with my colleagues"), Figure out ("I finally figured out how to solve the problem"). Write each in a sentence about YOUR real life.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Separable vs Inseparable Phrasal Verbs', description: 'Some phrasal verbs can be separated by an object, others cannot. SEPARABLE: "Turn off the light" OR "Turn the light off" OR "Turn it off." (pronoun MUST go in the middle) INSEPARABLE: "I came across a book." NOT "I came a book across." Common inseparable: come across, run into, get along with, look after, go through. Common separable: turn off, pick up, put off, give up, fill in. Write 3 sentences with separable phrasal verbs (correct position) and 3 with inseparable ones. This grammar distinction separates intermediate from advanced English.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Phrasal Verb Challenge - Natural Speech', description: 'Record yourself for 1 minute speaking ONLY using phrasal verbs instead of their formal equivalents. Example: instead of "I discontinued my studies" say "I gave up my studies." Instead of "I encountered problems" say "I ran into problems." Instead of "I tolerated the situation" say "I put up with the situation." This exercise forces your brain to think in natural English. Count how many phrasal verbs you use - aim for at least 8 in 1 minute.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 40,
    title: 'Formal vs Informal English',
    description: 'Day 40: Two thirds of your journey done - you are in the top league of English learners! Most people quit before reaching this point. Today you learn one of the most practical skills: switching between formal and informal English like a native speaker does naturally every day.',
    tasks: [
      { type: 'speaking', title: 'Same Topic - Two Different Styles', description: 'Speak about THIS topic twice: "I am going to be late for the meeting." First 1 minute: explain this formally as if speaking to your boss or professor. Then 1 minute: explain the same thing casually as if texting a friend. Formal: "I sincerely apologize for the inconvenience. Unfortunately I have been delayed due to unforeseen circumstances and will arrive approximately 15 minutes late." Casual: "Hey! Running late - traffic is crazy. Be there in 15, sorry!" Notice how different the same message sounds in different registers.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Formal vs Informal English Explained', description: 'Search YouTube for "formal vs informal English examples" and watch a 5-minute video. Write 5 pairs of formal and informal equivalents you learn (example: "I am unable to attend" vs "I cannot make it"). Notice: informal English uses contractions, slang, shorter sentences, and phrasal verbs. Formal English uses full forms, complex vocabulary, and longer sentences.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read Both Versions Aloud - Feel the Difference', description: 'Read both aloud and feel how different they are: FORMAL: "I am writing to express my sincere gratitude for the opportunity to interview with your esteemed organization. The discussion was both informative and inspiring, and I remain deeply interested in the position. I would welcome any feedback at your earliest convenience." INFORMAL: "Hey! Just wanted to say thanks so much for the interview today - it was really great! I am super excited about the role and would love to hear back from you. Let me know if you need anything from my side!" Read each version twice - match your voice tone to the style.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Formal and Informal Pairs - 10 Pairs', description: 'Learn both versions: Assist / Help, Purchase / Buy, Commence / Start, Terminate / End or Fire, Residence / Home, Inquire / Ask, Sufficient / Enough, Approximately / About, Obtain / Get, Commence / Begin. Now learn these informal expressions too: "sort out" (solve), "get back to you" (reply later), "no worries" (it is fine), "catch up" (meet), "totally" (completely). Write 5 sentences using formal vocabulary AND rewrite each in informal style. Knowing both makes you versatile in any situation.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Contractions - The Most Obvious Formal vs Informal Signal', description: 'Contractions are the fastest way to shift from formal to informal. Formal never uses contractions: "I am writing to inform you that I cannot attend." Informal always uses them: "I\'m writing to let you know I can\'t make it." Full list: I am/I\'m, you are/you\'re, he is/he\'s, they are/they\'re, do not/don\'t, cannot/can\'t, will not/won\'t, have not/haven\'t, should not/shouldn\'t. Take these informal sentences and rewrite them formally WITHOUT contractions: 1) "I\'m sorry I can\'t come to the meeting." 2) "We don\'t have enough time to finish this." 3) "She hasn\'t replied to my email yet." 4) "They won\'t be able to join us tomorrow."', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Switch Styles Live - Record Both Versions', description: 'Record yourself telling a short story about something that happened to you this week. Tell it TWICE: First version (30 sec): formal, as if presenting to your professor or manager. Second version (30 sec): informal, as if telling your best friend. Then listen back to both versions. Can you clearly hear the difference? If someone else heard these recordings, would they know you switched styles intentionally? This skill will serve you for the rest of your life.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
];

const patch = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected');
  for (const d of updates) {
    const totalXP = d.tasks.reduce((s, t) => s + t.xp, 0);
    await Day.updateOne(
      { dayNumber: d.dayNumber },
      { $set: { description: d.description, tasks: d.tasks, totalXP } }
    );
    console.log(`Updated Day ${d.dayNumber}`);
  }
  console.log('Done!');
  await mongoose.connection.close();
  process.exit(0);
};

patch().catch((e) => { console.error(e); process.exit(1); });
