require('dotenv').config();
const mongoose = require('mongoose');
const Day = require('../models/Day');

const updates = [
  {
    dayNumber: 11,
    title: 'Weather & Seasons',
    description: 'Day 11: Weather is the world\'s most popular conversation starter! Every English speaker uses it to begin a conversation. Today you will learn to describe weather, talk about seasons, and never feel stuck when someone says "Nice weather, isn\'t it?"',
    tasks: [
      { type: 'speaking', title: 'Describe Today\'s Weather Live', description: 'Look outside right now. Speak for 2 minutes: "Today in [your city] the weather is... The sky is... The temperature feels... I feel [happy/lazy/energetic] because of this weather." Use at least 5 weather words.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: BBC Weather Forecast', description: 'Search YouTube for "BBC Weather Forecast English" and watch a 3-minute video. Write down 5 expressions you hear like "scattered showers", "highs of 30 degrees", "clear skies expected". Notice how they use present continuous tense throughout.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Weather Paragraph Aloud', description: 'Read aloud slowly 3 times: "India has four main seasons. Summer is hot and dry. The monsoon brings heavy rain from June to September. Winter is cool and pleasant in most parts. Spring is short but beautiful, with flowers blooming everywhere. Each season changes the way we dress, eat, and feel."', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Weather Vocabulary - 10 Words', description: 'Learn with example sentences: Humid ("Mumbai is very humid in July"), Forecast ("The forecast says rain tomorrow"), Breeze ("A cool breeze is blowing"), Drizzle ("It is drizzling outside"), Foggy ("The road was foggy this morning"), Thunder ("I heard thunder last night"), Chilly ("December mornings are chilly"), Scorching ("It was a scorching afternoon"), Overcast ("The sky is overcast today"), Shower ("A sudden shower caught me outside"). Write each in YOUR own sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Present Continuous for Weather', description: 'We always use present continuous for weather happening right now. Rule: It IS + verb-ing. Write 5 sentences: "It is raining heavily." "The wind is blowing strongly." "The sun is shining brightly." "The temperature is rising." "Dark clouds are gathering." Now write 5 sentences about YOUR weather today.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Be a TV Weather Reporter!', description: 'Record yourself for 1 minute as a TV weather reporter. Start: "Good evening! Here is your weather report for today..." Mention today\'s weather, tomorrow\'s forecast, and one weather tip for viewers. Use hand gestures like a real reporter!', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 12,
    title: 'Shopping & Money',
    description: 'Day 12: Shopping English is practical English! You use it every week at a mall, market, or online. Today you will learn how to ask prices, negotiate, complain politely, and handle money conversations without hesitation.',
    tasks: [
      { type: 'speaking', title: 'Roleplay: You Are the Customer', description: 'Act both roles aloud. Customer: "Excuse me, how much is this shirt?" Shopkeeper: "It is 800 rupees, sir." Customer: "That is a bit expensive. Can you give a discount?" Shopkeeper: "I can give 10% off. Final price 720." Customer: "Okay. Can I pay by UPI?" Now make your own 6-line shopping conversation about something you want to buy.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: English Shopping Conversations', description: 'Search YouTube for "shopping conversation in English for beginners" and watch one video. Write 3 phrases the customer uses and 3 the shopkeeper uses. Notice polite words like "Excuse me", "Could I", "I would like".', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Shopping Dialogue Aloud', description: 'Read clearly: "A: Good afternoon! Can I help you? B: Yes, I am looking for a birthday gift for my mother. A: How about this scarf? It is on sale - 40% off today. B: Does it come in blue? A: Yes, here you go. Shall I gift wrap it? B: That would be wonderful, thank you!" Read it twice - once slowly, once at normal speed.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Shopping & Money - 10 Words', description: 'Learn: Discount ("There is a 50% discount today"), Receipt ("Keep your receipt for returns"), Refund ("I want a refund - this shirt has a hole"), Budget ("My budget is 5000 rupees"), Bargain ("I got a great bargain at the market"), Cashier ("Pay at the cashier counter"), Purchase ("I made three purchases online"), Exchange ("Can I exchange this for a smaller size?"), Warranty ("This phone has a 1-year warranty"), Overpriced ("This restaurant is overpriced"). Write each in your own sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'How much + Can I - Essential Shopping Grammar', description: 'Two essential patterns: 1) How much + is/are: "How much is this bag?" "How much are these shoes?" 2) Can/Could I + verb: "Can I try this on?" "Could I get a discount?" "Can I pay in instalments?" Write 5 "How much" questions and 5 "Can I" questions you might actually use while shopping.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Tell Your Best Shopping Story', description: 'Record yourself for 1 minute telling a real shopping experience. Include: Where did you go? What did you buy? How much did it cost? Did you bargain? Were you happy? Use past tense throughout.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 13,
    title: 'Travel & Directions',
    description: 'Day 13: Imagine you are at a railway station or new city and someone asks for directions in English - or YOU need help! Today you will master travel language so you never feel lost or speechless while traveling.',
    tasks: [
      { type: 'speaking', title: 'Give Directions From Your Home', description: 'Imagine a friend is at your nearest landmark. Give them directions to your home in English. Use: "Go straight for 200 meters", "Turn left at the traffic light", "Cross the bridge", "You will see a red building on your right", "It is opposite the medical store". Speak for 2 minutes with clear step-by-step directions.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Airport English Conversations', description: 'Search YouTube for "airport conversation in English" and watch a 5-minute video. Write: 3 things the passenger says at check-in, 2 things security asks, and 1 boarding announcement phrase. This real-world content prepares you for actual travel.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Travel Dialogue Aloud', description: 'Read clearly: "Tourist: Excuse me, could you help me? I am looking for the City Museum. Local: Of course! Go straight for about 5 minutes. Then turn right at the big roundabout. The museum is just after the park - you cannot miss it. Tourist: Thank you! How long will it take to walk? Local: About 10 minutes. Enjoy your visit!" Read it twice with natural feeling.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Travel & Directions - 10 Words', description: 'Learn: Itinerary ("Share your travel itinerary with family"), Departure ("Departure is at 6 AM from platform 3"), Layover ("We have a 2-hour layover in Delhi"), Landmark ("The hotel is near a famous landmark"), Detour ("We took a detour to avoid traffic"), Customs ("Declare items at customs"), Roundabout ("Turn left at the roundabout"), Transit ("I am in transit - just changing planes"), Boarding pass ("Show your boarding pass at the gate"), Luggage ("My luggage is too heavy"). Write each in your own sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Imperative Sentences for Directions', description: 'Directions use imperative - verb comes first, no subject needed. Examples: "Turn left." "Go straight." "Cross the road." "Take the second right." "Follow the signs to Gate 5." "Do not enter through that door." Write 8 direction sentences for getting from your home to your nearest bus stand or railway station.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Describe Your Dream Travel Destination', description: 'Record yourself for 1 minute about one place you desperately want to visit. Say: Where is it? Why do you want to go? What will you do there? Who will you take? Use "I want to...", "I would love to...", "I have always dreamed of..."', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 14,
    title: 'Work & Office',
    description: 'Day 14: Two weeks strong! Professional English gets you hired, promoted, and respected at work. Whether you work in an office, shop, or study for a job - today\'s lesson is directly useful for your career.',
    tasks: [
      { type: 'speaking', title: 'Answer: Tell Me About Yourself', description: 'Speak for 2 minutes answering the most common interview question. Include: your name, current work or study, key skills, career goal, and why you want to improve your English. Structure: past (where you came from) + present (what you do) + future (where you are going). Practice until it feels natural.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Office English Conversations', description: 'Search YouTube for "office English conversation for beginners" and watch one video. Notice: How do colleagues greet each other? How do they disagree politely? How do they end a conversation professionally? Write down 5 phrases you will use at your next job.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Professional Email Aloud', description: 'Read slowly and clearly: "Subject: Project Update. Dear Mr. Sharma, I hope this email finds you well. I am writing to update you on the XYZ project. We have completed 70% of the work and expect to finish by Friday. However, we need your approval on the budget before proceeding. Could you please review the attached document and share your feedback by tomorrow? Thank you for your time. Best regards, Priya." Read it twice focusing on professional tone.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Office & Career - 10 Words', description: 'Learn: Agenda ("Please send the meeting agenda in advance"), Collaborate ("We need to collaborate with the design team"), Delegate ("A good manager knows how to delegate tasks"), Feedback ("I need your feedback on this report"), Negotiate ("We need to negotiate the salary"), Milestone ("We reached an important project milestone"), Appraisal ("My annual appraisal is next month"), Networking ("Networking helped me find this job"), Resignation ("He submitted his resignation yesterday"), Probation ("I am on a 3-month probation period"). Write each in a sentence about YOUR work life.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Formal vs Casual - Same Meaning, Different Style', description: 'Offices require formal English. Learn these pairs and write 5 formal sentences. Casual to Formal: "Can you help?" becomes "Could you please assist me?", "I want" becomes "I would like", "Sorry" becomes "I sincerely apologize", "I need it fast" becomes "I would appreciate a prompt response", "What do you think?" becomes "Could I have your opinion on this?" Now write 5 formal sentences you might say at work.', xp: 15, duration: 10 },
      { type: 'confidence', title: '60-Second Professional Introduction', description: 'Record your perfect 60-second professional self-introduction. Structure: Name and current role (10 sec), Experience or education (15 sec), Key skills (15 sec), Your goal (10 sec), Closing line (10 sec). This is used in interviews, networking events, and first meetings. Make it sound confident and natural.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 15,
    title: 'Health & Body',
    description: 'Day 15: One quarter of your journey done! Health English is essential - you need it at a doctor\'s clinic, pharmacy, and gym. Today you will learn to describe symptoms, ask for medicine, and talk about your health habits confidently.',
    tasks: [
      { type: 'speaking', title: 'Describe Your Daily Health Habits', description: 'Speak for 2 minutes about your health routine. Answer these: How many hours do you sleep? Do you exercise? What do you eat for breakfast? Do you drink enough water? Do you have any health problems? Use "I usually...", "I try to...", "I should but I do not..." Being honest makes your speaking more natural!', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Doctor-Patient English Conversation', description: 'Search YouTube for "doctor patient conversation in English" and watch a short video. Write down: How does the patient describe their problem? What questions does the doctor ask? What advice does the doctor give? This exact conversation happens every day in clinics across India.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Doctor Dialogue Aloud', description: 'Read with feeling: "Doctor: Good morning! What seems to be the problem? Patient: I have had a terrible headache for three days. I also feel dizzy and have no appetite. Doctor: Do you have a fever? Patient: Yes, mild fever around 99 degrees. Doctor: Have you been sleeping properly? Patient: Not really - I have been working late. Doctor: You are exhausted. I am prescribing rest, plenty of fluids, and this painkiller. Come back in 3 days if you do not feel better." Read twice - once as doctor, once as patient.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Health & Body - 10 Words', description: 'Learn: Symptom ("Fever and cough are symptoms of flu"), Diagnosis ("The doctor gave a diagnosis of typhoid"), Prescription ("Take this prescription to the pharmacy"), Allergy ("I have an allergy to dust"), Chronic ("He has chronic back pain"), Nausea ("I feel nausea after eating oily food"), Inflammation ("The inflammation in my knee is painful"), Dosage ("Take one tablet - that is the correct dosage"), Immunity ("Good sleep builds your immunity"), Recuperate ("I need a week to recuperate after surgery"). Write each in a health sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Should / Must / Ought To - Health Advice', description: 'Modal verbs for advice: SHOULD (gentle): "You should drink more water." MUST (strong necessity): "You must take this medicine twice a day." OUGHT TO (similar to should): "You ought to sleep earlier." SHOULD NOT: "You should not eat spicy food with this condition." Write 6 health advice sentences - 2 with should, 2 with must, 2 with should not - as if advising a friend with a cold.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Roleplay: Explain Your Problem to a Doctor', description: 'Record yourself as a patient for 1 minute. Describe a real or imagined health problem. Include: What is the problem? Since when? How severe? Any other symptoms? What have you tried? Start with: "Good morning, Doctor. I have been feeling..." This builds confidence for real medical situations.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 16,
    title: 'Emotions & Feelings',
    description: 'Day 16: The most powerful English speakers are not those who use big words - they are those who express feelings clearly. Today you will go beyond "I am happy" and "I am sad" and express true emotions in rich, natural English.',
    tasks: [
      { type: 'speaking', title: 'Emotional Check-In', description: 'Speak for 2 minutes about your emotions today. Do NOT just say "I am happy" - go deeper! Try: "I am feeling a bit overwhelmed because...", "I am genuinely excited about...", "I feel proud of myself for...", "I am slightly nervous about...", "I am grateful for..." Using specific emotion words makes your English sound truly fluent.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Expressing Emotions in English', description: 'Search YouTube for "how to express feelings in English" and watch a short video. Write 5 expressions beyond basic happy/sad/angry. Look for phrases like "over the moon", "down in the dumps", "on edge", "pumped up", "choked up". These make you sound natural, not like a textbook.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Emotional Paragraph Aloud', description: 'Read with real emotion - feel the words: "It was the day of my exam results. I was terrified - my hands were shaking as I opened the website. Then I saw my score and I could not believe it. I had passed with distinction! I was absolutely overwhelmed with joy. I called my mother immediately and she burst into tears of happiness. That moment - the relief, the pride, the gratitude - I will never forget it." Read twice. The second time, let your voice show the emotions.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Deep Emotion Words - 10 Words', description: 'Go beyond basics: Overwhelmed ("I am overwhelmed with work"), Devastated ("She was devastated when her cat died"), Ecstatic ("He was ecstatic when he got the job"), Apprehensive ("I am apprehensive about the interview"), Nostalgic ("Old songs make me feel nostalgic"), Relieved ("I was so relieved when the exam ended"), Anxious ("She feels anxious in large crowds"), Fulfilled ("Helping others makes me feel fulfilled"), Resentful ("He felt resentful about being ignored"), Indifferent ("He seemed completely indifferent to the news"). Write each about a REAL moment in your life.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Feel + Adjective vs Feel Like + Noun', description: 'Two correct patterns: 1) Feel + adjective: "I feel nervous." "She feels proud." "We feel exhausted." 2) Feel like + noun/gerund: "I feel like a winner!" "I feel like crying." "I feel like giving up sometimes." WRONG: "I am feeling nervousness" - use the adjective, not the noun. Write 4 sentences using feel + adjective and 4 using feel like.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Tell Your Most Emotional Story', description: 'Record yourself for 1 minute telling a real moment when you felt a strong emotion - joy, fear, embarrassment, or pride. Make us FEEL what you felt. Use: "My heart was pounding", "I had butterflies in my stomach", "I was on cloud nine", "I wanted to disappear". The more honest you are, the better your English becomes.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 17,
    title: 'Hobbies & Interests',
    description: 'Day 17: "What do you do in your free time?" is one of the most common English conversation questions. Today you will give a rich, interesting answer that keeps a conversation going instead of a boring one-word reply like "cricket" or "music".',
    tasks: [
      { type: 'speaking', title: 'Talk About Your Hobby Like a Storyteller', description: 'Speak for 2 minutes about your favorite hobby. Do NOT just say "I like cricket." Instead: "I am passionate about cricket. I have been playing since I was 8. What I love most is the moment when you hit a perfect shot and the crowd cheers. It teaches me patience and teamwork. If I could, I would play every single day." Now do the same for YOUR hobby - make it vivid and personal.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Talking About Hobbies in English', description: 'Search YouTube for "talking about hobbies in English conversation" and watch a video. Notice: How do they expand beyond one sentence? How do they show enthusiasm? Write 3 phrases that sounded natural and interesting that you want to use yourself.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Hobby Conversation Aloud', description: 'Read with enthusiasm: "A: What do you enjoy in your free time? B: I am really into photography. I love capturing moments that tell a story - a child laughing, an old man reading, a flower after rain. A: How did you get started? B: My uncle gave me his old camera when I was fifteen. I was hooked from day one. A: Do you share your photos? B: Yes! I post on Instagram. Some photos have been appreciated by thousands of people - it feels incredible!" Read it twice like a real conversation.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Hobby & Passion - 10 Words', description: 'Learn: Passionate ("I am passionate about cooking"), Pursuit ("Photography is a creative pursuit"), Dedicated ("She is dedicated to learning music"), Therapeutic ("Gardening is therapeutic for me"), Amateur ("I am an amateur painter but improving fast"), Stimulating ("Reading is mentally stimulating"), Competitive ("I play competitive chess online"), Leisure ("I read novels in my leisure time"), Skilled ("He is highly skilled at woodworking"), Obsessed ("I am obsessed with learning languages"). Write each about YOUR hobbies.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Like / Love / Enjoy / Prefer - Important Differences', description: 'Like/Love/Enjoy + gerund (verb-ing): "I enjoy reading." "I love hiking." "I like cooking." Like/Love/Prefer + infinitive for specific occasions: "I like to read before bed." "I prefer to exercise in the morning." WRONG: "I enjoy to swim" - must be "I enjoy swimming". Write 3 sentences each using enjoy, love, and prefer about your hobbies.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Teach Your Hobby to a Beginner', description: 'Record yourself for 1 minute teaching someone who knows NOTHING about your hobby. How do you start? What equipment do you need? What is the first thing to learn? Why should they try it? Use clear, simple instructions. Teaching is the best test of how well you speak English!', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 18,
    title: 'Technology & Internet',
    description: 'Day 18: You are already using technology to learn English - well done! Today you will learn to TALK about technology in English. Tech is one of the biggest topics in job interviews, casual conversations, and daily life in India.',
    tasks: [
      { type: 'speaking', title: 'How Has Technology Changed Your Life?', description: 'Speak for 2 minutes honestly. Think about: How do you use your phone every day? How do you pay bills, book rides, order food? Has social media helped or hurt you? What technology could you not live without? Use: "Technology has completely changed the way I...", "Before smartphones, people used to...", "The biggest impact of technology on my life is..."', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Technology Vocabulary in English', description: 'Search YouTube for "technology vocabulary in English" and watch a 5-minute video. Focus on pronunciation of tech words - "algorithm", "bandwidth", "interface", "cybersecurity". These appear in job interviews constantly. Write down 5 new tech words you did not know before today.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Tech Paragraph Aloud', description: 'Read clearly and confidently: "Artificial Intelligence is no longer science fiction - it is part of our everyday lives. From the moment you unlock your phone with your face, to the time you ask a voice assistant to play music, AI is working silently behind the scenes. In India, millions of people use UPI for payments, Ola for rides, and Swiggy for food - all powered by sophisticated algorithms. The question is not whether technology will change your life. It already has. The real question is whether you are ready to keep up with it." Read it twice.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Technology - 10 Essential Words', description: 'Learn: Algorithm ("YouTube uses an algorithm to suggest videos"), Bandwidth ("Slow internet means low bandwidth"), Encryption ("WhatsApp uses encryption to protect messages"), Interface ("This app has a clean, simple interface"), Malware ("Never click unknown links - it could be malware"), Backup ("Always backup your important files"), Automation ("Automation is replacing repetitive jobs"), Cybersecurity ("Cybersecurity jobs are in high demand"), Scalable ("The startup built a scalable platform"), Streamline ("This software streamlines the billing process"). Write each in a tech sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Present Perfect - Talking About Tech Experiences', description: 'Present perfect connects past actions to now. Perfect for tech: "I have used this app for 2 years." "She has never tried online banking." "They have just launched a new feature." "Has your phone ever been hacked?" "I have not updated my password in months." Key words: already, yet, just, ever, never, for, since. Write 5 sentences about YOUR technology experiences.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Review Your Favorite App Like a YouTuber', description: 'Record yourself for 1 minute reviewing your favorite app or gadget. Cover: What is it? What does it do? 3 best features? Who should use it? Rating out of 10? Start: "Hey everyone! Today I am going to review..." Sound enthusiastic - tech reviewers are always energetic!', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 19,
    title: 'Nature & Environment',
    description: 'Day 19: Environmental topics appear in English exams, group discussions, and job interviews constantly. "What can we do about climate change?" is asked in IELTS, job interviews, and college admissions. Today you will speak about nature with passion.',
    tasks: [
      { type: 'speaking', title: 'Describe Nature in Your City', description: 'Speak for 2 minutes about nature where you live. Answer: Is your city clean or polluted? Are there parks or trees nearby? Has the environment changed in the last 10 years? What do YOU personally do to protect the environment? Use: "The air quality in my city...", "I have noticed that...", "One thing I try to do is..." Being honest makes your speaking more natural.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: A Short Nature Documentary Clip', description: 'Search YouTube for "BBC Earth short clip" or "nature documentary English 5 minutes" and watch one. Pay attention to the narrator\'s voice - calm, clear, descriptive. Write 3 sentences from the video that you found beautiful or interesting. Notice how they describe animals and landscapes with vivid adjectives.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Environmental Paragraph Aloud', description: 'Read with conviction: "India is one of the most biodiverse countries in the world, home to tigers, elephants, and thousands of plant species. But this natural wealth is under serious threat. Every year, millions of trees are cut down and rivers are poisoned with industrial waste. Climate change is not a distant problem - farmers across India already face unpredictable monsoons and extreme heat waves. The good news? Every individual action matters. Planting a tree, refusing plastic, saving water - these small habits, multiplied by a billion people, can change everything." Read it twice with passion.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Environment & Nature - 10 Words', description: 'Learn: Biodiversity ("The Amazon has incredible biodiversity"), Deforestation ("Deforestation destroys animal habitats"), Carbon footprint ("Flying increases your carbon footprint"), Emissions ("Car emissions cause air pollution"), Sustainable ("We need sustainable farming methods"), Drought ("Parts of Rajasthan face severe drought"), Conservation ("Tiger conservation has increased their numbers"), Renewable ("Solar power is a renewable energy source"), Ecosystem ("Bees are vital to the ecosystem"), Glacier ("Himalayan glaciers are melting fast"). Write each in a sentence related to India.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Comparative & Superlative Adjectives', description: 'Comparatives show differences. Short words: add -er/-est (hot, hotter, hottest). Long words: more/most (polluted, more polluted, most polluted). Irregular: good/better/best, bad/worse/worst. Write these and add 5 of your own: "The air in villages is cleaner than in cities." "The Ganges is more polluted than 20 years ago." "Solar energy is the most sustainable option." "Plastic is worse for oceans than any other waste." "Winters are colder now than before."', xp: 15, duration: 10 },
      { type: 'confidence', title: 'One-Minute Environmental Speech', description: 'Record a passionate 1-minute speech as if speaking at your school or college. Topic: "Why should young Indians care about the environment?" Use: "Imagine a world where...", "Our generation will be the last to...", "Every single one of us has the power to..." Speak from the heart - passion is more important than perfection!', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 20,
    title: 'Sports & Games',
    description: 'Day 20: One third of your journey complete - you are building real habits! Sports is the universal language. Indians talk about cricket the way Brazilians talk about football. Today you will express your sports passion in English with the same energy you feel when India wins a match!',
    tasks: [
      { type: 'speaking', title: 'Talk About Your Favorite Sport With Passion', description: 'Speak for 2 minutes about your favorite sport as if telling a friend why they MUST try it. Cover: What is the sport? Why do you love it? Who is your favorite player and why? What is the most exciting moment you remember? Use: "I was on the edge of my seat", "It was absolutely breathtaking", "I could not believe what I just saw!"', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: English Cricket or Sports Commentary', description: 'Search YouTube for "cricket commentary English highlights" or your favorite sport + "English commentary". Watch 5 minutes and write 5 commentary phrases like "What a stunning catch!", "He is absolutely on fire today!", "The crowd has gone completely wild!" These energetic phrases are great for building expressive English.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Sports Paragraph With Energy', description: 'Read with maximum excitement: "It was the last over. India needed 12 runs to win the World Cup final. The stadium was electric - 90,000 fans holding their breath. The first ball - a six! The crowd erupted. The second ball - a four! Now only 2 runs needed from 4 balls. Dhoni stepped forward, hit a clean shot over mid-wicket, and the ball soared into the night sky. India had won. Players ran onto the field, fans wept with joy, and a billion people celebrated as one. That night, cricket did not just win a trophy - it united a nation." Read it twice - louder the second time!', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Sports - 10 Power Words', description: 'Learn: Underdog ("India was the underdog but won"), Stamina ("Marathon runners need incredible stamina"), Substitute ("The substitute scored the winning goal"), Penalty ("The referee awarded a penalty kick"), Momentum ("After three wins, the team had great momentum"), Controversial ("It was a controversial decision by the referee"), Dominant ("She was completely dominant in the final set"), Comeback ("What an incredible comeback after losing the first set!"), Rivalry ("The India-Pakistan cricket rivalry is legendary"), Qualifier ("We won the qualifier and reached the finals"). Write each in a sentence about real sport.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Simple Past for Reporting Sports Events', description: 'Sports news always uses simple past tense: "India beat Pakistan by 6 wickets." "Rohit Sharma scored a magnificent century." "The referee showed a red card in the 89th minute." "She broke the world record by 0.3 seconds." "Our team lost the final despite playing brilliantly." Write 5 sentences about a real match you watched recently. Include the score, key player, and how you felt.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Live Match Commentary - 1 Minute!', description: 'The most fun task yet! Record yourself giving LIVE commentary of an imaginary or real match for 1 minute. Use an excited, fast voice. Include: current score, a big moment, crowd reaction, and your personal opinion. Start: "And we are LIVE here at the stadium! The score is..." This builds speed, fluency, and confidence like nothing else!', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
];

const patch = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected');
  for (const d of updates) {
    const totalXP = d.tasks.reduce((s, t) => s + t.xp, 0);
    await Day.updateOne(
      { dayNumber: d.dayNumber },
      { $set: { description: d.description, tasks: d.tasks, totalXP } }
    );
    console.log(`Updated Day ${d.dayNumber}`);
  }
  console.log('Done!');
  await mongoose.connection.close();
  process.exit(0);
};

patch().catch((e) => { console.error(e); process.exit(1); });
