require('dotenv').config();
const mongoose = require('mongoose');
const Day = require('../models/Day');

const updates = [
  {
    dayNumber: 41,
    title: 'Reading Comprehension',
    description: 'Day 41: Reading is the fastest way to absorb vocabulary, grammar, and ideas simultaneously. Today you will not just read - you will read actively, like a detective hunting for meaning, structure, and language patterns.',
    tasks: [
      { type: 'speaking', title: 'Summarize a Paragraph in Your Own Words', description: 'Read this paragraph once, then close your eyes and speak a 2-minute summary in your own words: "India is experiencing one of the fastest digital transformations in human history. In just 10 years, mobile internet users grew from 50 million to over 700 million. Today a vegetable seller in a small town accepts UPI payments, a farmer checks crop prices on WhatsApp, and a student in a village attends live classes on a smartphone. This revolution did not happen by accident - it was driven by affordable data, cheap smartphones, and government initiatives like Digital India." What was the main idea? What details supported it? What surprised you?', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Active Reading Strategies in English', description: 'Search YouTube for "how to improve reading comprehension in English" and watch one video. Write down 3 active reading strategies - like identifying the main idea, looking for topic sentences, and inferring meaning from context. These strategies work for IELTS reading, news articles, and any English text you encounter.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Article and Answer Questions', description: 'Read aloud then answer: "The concept of jugaad - the Indian art of creative problem-solving with limited resources - has caught the attention of business schools worldwide. From a bicycle pump converted into a ventilator to a washing machine built from a motorcycle engine, Indian innovators have shown that necessity truly is the mother of invention. Harvard Business School now teaches jugaad as a case study in frugal innovation. What started as a survival strategy for resource-scarce environments has become a globally admired approach to business." Questions: 1) What is jugaad? 2) Why do business schools study it? 3) Give one example from the text. Answer all three in English.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Reading & Comprehension - 10 Words', description: 'Learn: Infer ("From his tone, I could infer that he was angry"), Deduce ("She deduced the answer from the clues given"), Paraphrase ("Can you paraphrase that in simpler words?"), Context ("The meaning depends on the context of the sentence"), Implicit ("The implicit message was that he wanted to leave"), Explicit ("The instructions were very explicit and clear"), Summarize ("Please summarize the article in three sentences"), Coherent ("Her argument was coherent and well-structured"), Comprehend ("I could not comprehend the legal document"), Skim ("Skim the article first to get the general idea"). Write each in a reading-related sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'WH-Questions for Deep Comprehension', description: 'The six WH-questions unlock the meaning of any text. Practice answering each type about the jugaad paragraph above: WHO - "Who is teaching jugaad as a case study?" WHAT - "What is the definition of jugaad?" WHERE - "Where is jugaad being studied internationally?" WHEN - "When did this concept gain global attention?" WHY - "Why is jugaad admired worldwide?" HOW - "How did jugaad begin?" Now write 6 WH-questions about ANY topic you read today - one for each question word.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Teach What You Just Read', description: 'Record yourself for 1 minute explaining the jugaad concept to someone who has never heard of it before. Use your own words completely - do not re-read the passage. Explain: what it means, give a different example than the text, and say why you think it is impressive. Teaching what you read is the highest form of comprehension - if you can explain it simply, you truly understood it.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 42,
    title: 'Listening Skills',
    description: 'Day 42: Six weeks of learning - phenomenal commitment! Listening is the most underestimated English skill. Most people focus on speaking but forget that you cannot have a real conversation if you cannot understand what the other person is saying. Today we fix that.',
    tasks: [
      { type: 'speaking', title: 'Shadow a Native Speaker', description: 'This is the most powerful listening-to-speaking technique. Listen to any 30 seconds of spoken English, then immediately repeat it trying to match the exact speed, rhythm, and pronunciation. Do this 3 times with 3 different sentences. Then speak for 1 minute about what you noticed - was the speed surprising? Did words sound different from how you imagined? Did you catch every word? Shadowing builds both listening and speaking simultaneously.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Improve Your English Listening Skills', description: 'Search YouTube for "English listening practice for beginners intermediate" and watch a 5-minute video specifically designed for listening practice - not just any video. Write: 5 words you heard clearly, 2 sentences you had to replay to understand, and 1 thing about the speaker\'s accent or speed that you noticed. The goal today is active, focused listening - not passive background listening.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Dialogue Aloud Focusing on Natural Rhythm', description: 'Read this at NATURAL conversational speed - not slowly: "A: Have you been following the news lately? B: Not really - what is happening? A: Apparently they are building a new metro line through our area. B: Oh really? That would be fantastic - the traffic here is unbearable. A: Exactly. They say it will be ready in three years. B: Three years? I will believe it when I see it. A: Ha! Fair enough. But even if it takes five, it would transform this whole neighborhood. B: You are right about that. Property prices alone will double." Read it three times - each time faster and more naturally.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Listening & Communication - 10 Words', description: 'Learn: Attentive ("She was an attentive listener who never interrupted"), Clarify ("Could you clarify what you mean by that?"), Paraphrase ("Let me paraphrase what you said to check I understood"), Distraction ("Put your phone away - it is a major distraction"), Tone ("I could tell from his tone that he was upset"), Comprehend ("I could not comprehend the speaker\'s strong accent"), Absorb ("It takes time to absorb new language patterns"), Perceive ("She perceived a hint of sarcasm in his words"), Interpret ("How do you interpret this sentence?"), Ambient ("The ambient noise made it hard to hear"). Write each in a listening-related sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Question Tags - Essential for Conversations', description: 'Question tags check understanding and keep conversations going. Positive sentence + negative tag: "It is raining, isn\'t it?" "You speak English, don\'t you?" "She passed the exam, didn\'t she?" Negative sentence + positive tag: "It is not working, is it?" "You have not eaten, have you?" "He did not call, did he?" Rule: if the main verb is positive, the tag is negative - and vice versa. Write 6 sentences with correct question tags about things happening around you right now. These are used constantly in natural English conversations.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Shadowing Challenge - Record Yourself', description: 'Find any 1-minute English video on YouTube - a news clip, a speech, or a conversation. Play 10 seconds, pause, repeat exactly. Play the next 10 seconds, pause, repeat. Do this for the full minute. Then record yourself speaking that same content from memory. Compare your version to the original. This one exercise, done daily, will transform your English accent, rhythm, and fluency faster than anything else.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 43,
    title: 'Writing Skills',
    description: 'Day 43: Writing is thinking made visible. A person who writes well in English thinks clearly in English. Today you will practice writing sentences and paragraphs that are clear, organized, and powerful - skills that help you in exams, emails, social media, and beyond.',
    tasks: [
      { type: 'speaking', title: 'Explain Why Writing Matters to You', description: 'Speak for 2 minutes about writing in English. Answer honestly: Do you find writing easy or difficult? Why? What kind of writing do you do in English - WhatsApp messages, emails, notes? What would you like to write better - stories, reports, essays? Have you ever written something in English that you were proud of? Your honest reflection on writing will help you identify exactly where to focus your energy today.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: How to Write Better in English', description: 'Search YouTube for "how to improve English writing skills" and watch one video. Write down 3 specific tips you will apply immediately. Common excellent tips: write a topic sentence first, use one idea per paragraph, vary your sentence length, avoid repeating the same word twice, and always read your writing aloud to check if it sounds natural.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Well-Written Paragraph - Then Analyze It', description: 'Read aloud: "Consistency is the most underrated quality in any learner. Many students study intensively for a week and then disappear for a month. They are like a fire that blazes brilliantly but burns out quickly. The learner who studies for just 30 minutes every single day without exception will always outperform the occasional marathon studier. This is not an opinion - it is supported by decades of research on how the human brain forms long-term memories. Small, repeated actions build neural pathways. Large, infrequent efforts do not." Now identify: 1) the topic sentence, 2) the supporting evidence, 3) the conclusion, 4) one metaphor used. Read it again after analyzing.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Writing & Structure - 10 Words', description: 'Learn: Coherent ("A coherent paragraph has one clear idea"), Concise ("Keep your writing concise - remove unnecessary words"), Elaborate ("Could you elaborate on your second point?"), Articulate ("She was able to articulate her ideas very clearly"), Draft ("Always write a first draft without worrying about perfection"), Revise ("Good writers revise their work multiple times"), Transition ("Use transition words to connect your paragraphs"), Thesis ("Your thesis statement should appear in the first paragraph"), Persuasive ("The essay was highly persuasive"), Analytical ("The report required strong analytical writing"). Write each in a writing-context sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Simple, Compound and Complex Sentences', description: 'Good writing uses all three: SIMPLE (one idea): "I study English every day." COMPOUND (two ideas joined by and/but/so/or): "I study English every day, and I am seeing real progress." COMPLEX (main idea + dependent clause): "Although it is difficult, I study English every day because I believe it will change my life." Now write this paragraph using all three types: Write about your English learning journey using 2 simple sentences, 2 compound sentences, and 2 complex sentences. Mix them naturally - variety makes writing interesting to read.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Write a Paragraph and Read It Aloud', description: 'Write a short paragraph (5-7 sentences) about one of these topics: 1) The most important lesson you have learned in life, 2) A person who inspired you, or 3) Why you started this 60-day challenge. Then record yourself reading it aloud clearly. Does it sound like something you are proud of? If not, rewrite one sentence that bothered you. Writing and then reading your own words is the most direct path to seeing your real English level.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 44,
    title: 'Speaking Fluency',
    description: 'Day 44: Fluency does not mean speaking perfectly - it means speaking smoothly and continuously without long uncomfortable pauses. Today is entirely dedicated to the one thing that builds fluency faster than anything else: speaking without stopping.',
    tasks: [
      { type: 'speaking', title: '2 Minutes Non-Stop - No Pausing Allowed', description: 'Set a timer for 2 minutes. Speak on this topic without stopping for even 1 second: "Describe everything you did from the moment you woke up this morning until right now." If you run out of things to say, connect to something else: "This reminds me of...", "Something related to this is...", "Actually, while I was doing that, I was also thinking about..." The rule is simple: your mouth must not stop for 2 full minutes. Fluency is a physical habit - it must be trained.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: How Fluent Speakers Connect Words', description: 'Search YouTube for "natural English connected speech" or "how to speak English fluently and naturally" and watch a 5-minute video. Notice specifically: how speakers link words together ("want to" becomes "wanna", "going to" becomes "gonna" in casual speech), how they use filler words naturally ("well", "you know", "actually", "basically"), and how they pause for emphasis NOT out of confusion. These are the secrets of sounding natural.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Paragraph at 3 Different Speeds', description: 'Read this paragraph THREE times: once slowly, once at normal speed, once fast: "The secret to speaking English fluently is deceptively simple - you must speak more English than you are comfortable speaking. Most learners wait until they feel ready. They study grammar, memorize vocabulary, and wait for the perfect moment when they will finally feel confident enough to open their mouth. That moment never comes. Fluency is not a destination you arrive at after preparation. It is a muscle you build through daily use. Speak before you are ready. Speak when you are scared. Speak when you make mistakes. Especially then. Because every mistake is a step toward the fluency you are seeking." Which speed felt most natural? That is your target pace.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Fluency Fillers and Connectors', description: 'Fluent speakers use these naturally - learn them as habits: Thinking fillers (buy time without silence): "Well...", "Let me think...", "That is a great question...", "How should I put this..." Connectors (link ideas): "Not only that, but...", "What is more...", "Having said that...", "At the same time..." Emphasis: "What I really mean is...", "The key point here is...", "Above all...", "More importantly..." These phrases do not just fill silence - they make you sound organized and thoughtful. Practice using at least 5 of these in today\'s confidence task.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Discourse Markers - The Grammar of Fluency', description: 'Discourse markers connect ideas and signal what is coming next. They are the skeleton of spoken fluency. To add information: "Furthermore", "Moreover", "In addition", "Not only that". To contrast: "However", "Nevertheless", "On the other hand", "That said". To give an example: "For instance", "Such as", "To illustrate". To conclude: "Therefore", "As a result", "In conclusion", "All in all". Write a 6-sentence spoken response to this question: "What is the best way to learn a new language?" - using at least 4 different discourse markers. Then read it aloud smoothly.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'The 1-Minute No-Stop Speech', description: 'Record yourself speaking for exactly 1 minute on this topic without ANY pause longer than 1 second: "If I could give one piece of advice to someone starting to learn English today, it would be..." Use filler phrases if needed. Use connectors. Change direction if you run out of ideas. But DO NOT STOP. Listen back and count how many times you paused for more than 2 seconds. Your goal is zero pauses. Record again if needed. This exercise done daily for 1 week will transform your fluency.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 45,
    title: 'Grammar Mastery',
    description: 'Day 45: Three quarters of your journey complete - you are remarkable! Grammar is the architecture of language. You do not need to know every rule - you need the most important ones to work automatically. Today we review and master the grammar patterns that appear most in real English.',
    tasks: [
      { type: 'speaking', title: 'Speak 10 Grammatically Perfect Sentences', description: 'Speak 10 sentences about your daily life - one at a time - focusing on making each one grammatically perfect before moving to the next. After each sentence, ask yourself: Did I use the right tense? Is the subject-verb agreement correct? Did I use the right article (a/an/the)? Did I need any preposition? This is NOT about speed - it is about precision. Slow, accurate English sounds more intelligent than fast, incorrect English.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Common Grammar Mistakes Indians Make in English', description: 'Search YouTube for "common English grammar mistakes Indians make" and watch a 5-minute video. Write down 5 mistakes you recognize making yourself. Common ones: "I am having a car" (wrong) vs "I have a car" (right), "She is not knowing" vs "She does not know", "I am doing since 2 years" vs "I have been doing for 2 years". Recognizing your own errors is the first step to correcting them.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Grammar-Rich Paragraph and Identify Structures', description: 'Read aloud: "If I had studied harder in school, I would have scored better in my exams. However, I do not believe in regrets. What matters is what I am doing now. I have been learning English consistently for 45 days, and the progress I have made has surprised even me. By the time I finish this 60-day challenge, I will have completed over 270 tasks. Grammar has always been the part of English that I found most challenging - but I am beginning to see it not as a set of rules to memorize, but as a set of tools to use." Identify: 1 conditional sentence, 1 present perfect, 1 future perfect, 1 present continuous, 1 contrast connector.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Grammar Terms You Should Know', description: 'Learn these terms so you can understand grammar explanations: Subject ("In this sentence, I is the subject"), Predicate ("The predicate is everything after the subject"), Clause ("A clause has a subject and a verb"), Modifier ("An adjective is a modifier that describes a noun"), Auxiliary ("Have, be, and do are auxiliary verbs"), Infinitive ("To speak is the infinitive form"), Gerund ("Speaking is a gerund - a verb used as a noun"), Participle ("Running water - running is a participle"), Conjunction ("But and although are conjunctions"), Syntax ("The syntax of this sentence is unusual"). Write each in your own example sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'The 5 Grammar Rules That Matter Most', description: 'Master these 5 patterns - write 3 sentences for each: 1) Subject-verb agreement: "She speaks" not "She speak". 2) Correct tense choice: "I have eaten" (recent past) vs "I ate" (completed past). 3) Articles: "a" for first mention, "the" for known/specific things. 4) Prepositions: "interested IN", "good AT", "arrive IN a city/AT a place". 5) Word order: adjectives before nouns, adverbs after verbs. Identify which rule you find hardest and write 5 extra sentences practicing just that one.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Teach One Grammar Rule Confidently', description: 'Record yourself for 1 minute teaching ONE grammar rule to a beginner student. Choose a rule you have mastered - could be present perfect, conditional sentences, or articles. Explain: What is the rule? Why do we use it? Give 3 examples. Give 1 common mistake to avoid. Teaching grammar forces you to understand it deeply, not just passively know it. If you can explain it clearly, you own it.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 46,
    title: 'Tenses Review',
    description: 'Day 46: Tenses are the time machine of English. They tell your listener exactly WHEN something happened, is happening, or will happen. Today you will take a complete tour through all major tenses using real stories from your own life.',
    tasks: [
      { type: 'speaking', title: 'Your Life in Three Tenses', description: 'Speak for 2 minutes covering all three time periods: PAST (30 sec): "When I was a child, I used to... I grew up in... I always wanted to..." PRESENT (1 min): "Right now, I am studying... I work/study at... I am currently trying to... I have been learning English for..." FUTURE (30 sec): "Next year, I am going to... I will definitely... By the time I am 30, I hope to..." Using all three tenses in one speech is what advanced English speakers do naturally. Practice until the transitions feel smooth.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: All English Tenses Explained Simply', description: 'Search YouTube for "all English tenses explained simply" and watch a 5-minute revision video. Do not just watch - actively identify which tense is being used each time the teacher gives an example. Write 3 tenses you still find confusing and 2 tenses you now feel confident about. Tense confusion is the most common grammar issue for Indian English speakers - today we address it directly.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Tense-Rich Paragraph Aloud', description: 'Read slowly, noticing every tense used: "I started this English challenge 46 days ago. When I began, I was nervous and unsure. I had never recorded my own voice before, and the first time I heard myself speak I almost gave up. But I carried on. I have been speaking, listening, reading, and writing every single day. By tomorrow, I will have completed 46 days. By the end of this month, I will have finished the entire 60-day journey. I am already a different person from who I was on Day 1. And the best part? I am just getting started." Identify every tense used: simple past, past perfect, present perfect, present continuous, future perfect, future simple.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Time Expressions for Each Tense', description: 'Learn which time words go with which tense: SIMPLE PAST: yesterday, last week, in 2020, ago, once, when I was young. PRESENT PERFECT: just, already, yet, ever, never, since, for, recently. PRESENT CONTINUOUS: now, at the moment, currently, these days. FUTURE SIMPLE: tomorrow, next week, soon, in the future, one day. PAST PERFECT: by the time, before, already, never before, until then. Write 2 sentences for each tense using the time expressions above. Getting the time expression right makes your tense choice sound natural.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Present Perfect vs Simple Past - The Most Confused Pair', description: 'This is the most common tense error in Indian English. SIMPLE PAST - finished action at a specific time: "I visited Delhi in 2019." "She called me yesterday." PRESENT PERFECT - past action connected to present, no specific time: "I have visited Delhi." (and that experience is relevant now) "She has called me." (recently, and it is still relevant) KEY TEST: If you can add "yesterday" or "in 2019" - use simple past. If you cannot - use present perfect. Correct these errors: 1) "I have met him last week." 2) "She visited three countries in her life." 3) "Did you ever try sushi?" Write 4 correct sentences using each tense.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Your Life Journey in Multiple Tenses', description: 'Record yourself for 1 minute telling the story of your life journey using at least 5 different tenses: where you grew up (simple past), what your childhood was like (past continuous), what you have achieved so far (present perfect), what you are doing now (present continuous), and where you are going (future). This is essentially the perfect answer to "Tell me about yourself" - the most asked question in English interviews. Make it personal, make it real, make it memorable.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 47,
    title: 'Articles & Prepositions',
    description: 'Day 47: Articles and prepositions are the smallest words in English but they cause the biggest problems for Indian learners. We do not have articles in Hindi, so "a", "an", and "the" feel unnatural. Today you will crack this once and for all.',
    tasks: [
      { type: 'speaking', title: 'Describe Your Room Using Articles and Prepositions', description: 'Speak for 2 minutes describing exactly where things are in your room. Every sentence must use a preposition AND the correct article. Example: "There is a table near the window. The table has a laptop on it. My phone is on the desk beside the bed. There is a poster above the door. My bag is under the chair in the corner." Focus on getting a/an/the right - this is the hardest part for most Indian English speakers. Record yourself and listen back for any article mistakes.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Articles and Prepositions Explained for Indian Learners', description: 'Search YouTube for "articles a an the explained for Indian students" and watch a 5-minute video. Write the 3 main rules for using "the" (specific, unique, second mention) and 2 rules for when NOT to use any article (general plural nouns, names of people, countries mostly). Articles are a system - once you understand the logic, they stop feeling random.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This and Count Every Article', description: 'Read aloud and count every a, an, and the: "The sun was setting over the Arabian Sea as I arrived at the Mumbai airport for the first time. I had expected a big city but nothing had prepared me for the scale of it. A taxi driver with a huge smile offered to take me to the hotel. The drive through the city took an hour, and I spent every minute with my face pressed against the window. The streets were alive with people, colour, and the smell of food from a hundred different stalls. By the time I reached the hotel, I was exhausted but completely in love with the city." Count them. Were there more than you expected?', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Preposition Combinations - Learn These as Fixed Phrases', description: 'These prepositions are FIXED - do not guess them, memorize them: Interested IN, Good AT, Afraid OF, Responsible FOR, Dependent ON, Similar TO, Different FROM, Married TO, Excited ABOUT, Famous FOR. Also: arrive IN a city, arrive AT a building, in the morning/afternoon/evening, at night, on Monday/Tuesday, in January/March, at 5 o\'clock. Write 10 sentences using these preposition combinations correctly. These exact combinations are tested in IELTS and job applications.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'The 3 Rules for Articles That Cover 90% of Cases', description: 'RULE 1 - Use A/AN for something mentioned for the FIRST time or one of many: "I saw a dog." "She is a doctor." (one of many doctors) RULE 2 - Use THE for something SPECIFIC or ALREADY KNOWN: "The dog bit me." (the specific one I mentioned) "The sun is hot." (there is only one sun) RULE 3 - Use NO article for general plural nouns and proper nouns: "Dogs are loyal." "India is beautiful." "I love music." Now fill in the blanks with a, an, the, or nothing: "___ Himalayas are ___ highest mountains in ___ world. ___ mountain called K2 is ___ second highest. ___ mountains attract ___ thousands of ___ climbers every year." Check your answers by reading aloud - does it sound right?', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Describe Your Journey to This Point', description: 'Record yourself for 1 minute describing your English learning journey since Day 1 of this challenge. Use correct articles and prepositions throughout. Pay extra attention: every time you mention a specific thing use "the", every first mention use "a/an", and every general statement use no article. After recording, listen back specifically hunting for article mistakes. Correcting yourself on playback is one of the most effective learning techniques that exists.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 48,
    title: 'Conjunctions & Connectors',
    description: 'Day 48: The difference between someone who speaks English and someone who speaks English well is connectors. They are the glue that holds ideas together and makes speech flow like a river instead of jumping like stepping stones. Today you will master them.',
    tasks: [
      { type: 'speaking', title: 'Connect 5 Ideas Into One Flowing Speech', description: 'Speak for 2 minutes on this topic: "What has this 60-day English challenge taught you so far?" But here is the rule - every sentence must be connected to the next one using a connector. You cannot start a new sentence without linking it: "I started this challenge because I wanted to improve my English. However, what I did not expect was how much confidence I would gain. Not only have my vocabulary and grammar improved, but I have also become more willing to speak in public. As a result, my colleagues have noticed the change. Furthermore, I have realized that..." Keep going - do not stop.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Linking Words and Connectors in English', description: 'Search YouTube for "linking words and connectors English" and watch a 5-minute video. Write 3 connectors for each category: adding information (and, also, furthermore), contrasting (but, however, although), giving reasons (because, since, as), showing results (so, therefore, as a result), and giving examples (for example, such as, for instance). Knowing which category a connector belongs to helps you choose the right one.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Connector-Rich Paragraph Aloud', description: 'Read smoothly - notice how each sentence flows into the next: "Learning a language as an adult is challenging; however, it is far from impossible. Many people believe that children learn languages more easily because their brains are more flexible. While this is partly true, adults actually have several significant advantages. For instance, we already understand complex grammar from our mother tongue. Furthermore, we can set clear goals, manage our time, and use strategies that children simply cannot access. As a result, a motivated adult learner can achieve remarkable fluency in just one to two years. Therefore, age is not a barrier - it is simply a different path to the same destination." Read it twice.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: '10 Connectors That Will Upgrade Your English Immediately', description: 'Learn with examples: Nevertheless ("The task was difficult; nevertheless, she completed it"), Consequently ("He did not study; consequently, he failed"), Meanwhile ("She was cooking; meanwhile, I set the table"), In contrast ("Delhi is very hot in summer; in contrast, Shimla is cool"), Provided that ("I will help you provided that you help me in return"), Despite ("Despite the rain, we went for a walk"), Whereas ("I prefer tea whereas my sister loves coffee"), Hence ("She worked hard; hence, her success"), Albeit ("It was a small victory, albeit an important one"), Nonetheless ("The journey was tiring; nonetheless, we enjoyed it"). Write each in your own sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Subordinating vs Coordinating Conjunctions', description: 'COORDINATING conjunctions join two equal ideas (remember FANBOYS): For, And, Nor, But, Or, Yet, So. "I wanted to go, but I was tired." "She studied hard, so she passed." SUBORDINATING conjunctions make one idea dependent on another: although, because, since, while, unless, until, even though, as soon as. "Although I was tired, I kept going." "Because she studied hard, she passed." KEY difference: coordinating goes IN THE MIDDLE. Subordinating can go AT THE START or MIDDLE. Write 4 sentences with coordinating and 4 with subordinating conjunctions about your English learning experience.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'The Connected Speech Challenge', description: 'Record yourself for 1 minute talking about any topic - your city, your work, your dreams. The only rule: use at least 8 different connectors. After recording, count the connectors you used. Did you reach 8? If not, record again. Aim for variety - do not use "and" and "but" for everything. The goal is for your speech to sound like one flowing piece of connected thought, not a list of separate sentences. This is the hallmark of advanced English.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 49,
    title: 'Reported Speech',
    description: 'Day 49: Just 11 days left - you are almost there! Reported speech is how we tell others what someone said. It appears everywhere - in news, gossip, stories, interviews, and academic writing. Mastering it makes your English sound sophisticated and accurate.',
    tasks: [
      { type: 'speaking', title: 'Report a Conversation You Had Recently', description: 'Speak for 2 minutes reporting a real conversation you had with someone in the last few days. Do NOT use direct quotes - use reported speech throughout: "My mother told me that I should eat more vegetables." "My friend asked me whether I had finished the project." "My manager said that the presentation had gone very well." "The shopkeeper told me that the price had gone up." Include at least 5 reported statements and 2 reported questions. This is exactly the skill tested in IELTS speaking and academic English assessments.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Direct and Reported Speech Explained', description: 'Search YouTube for "direct and indirect speech English examples" and watch a 5-minute video. Write the 3 key changes that happen when converting to reported speech: 1) verb tense shifts back (is becomes was, will becomes would), 2) pronouns change (I becomes he/she, we becomes they), 3) time words change (today becomes that day, yesterday becomes the day before). Write 3 example conversions from the video.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This News Report Aloud - Full of Reported Speech', description: 'Read like a news anchor: "The Prime Minister announced yesterday that the government was committed to creating 10 million jobs over the next three years. He stated that infrastructure investment would be the primary driver of this growth. The Finance Minister added that the budget allocation for job creation had been doubled. Meanwhile, the opposition leader claimed that these were empty promises and demanded that the government present concrete data. An independent economist told reporters that the targets were ambitious but achievable if reforms were implemented quickly. Citizens interviewed on the street said they were cautiously optimistic but wanted to see results." Read it twice, noticing every reporting verb used.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Reporting Verbs - 10 That Go Beyond Said', description: 'Using only "said" is boring. Learn these precise reporting verbs: Claimed ("He claimed that he had never been there"), Insisted ("She insisted that she was telling the truth"), Admitted ("He admitted that he had made a mistake"), Suggested ("She suggested that we try a different approach"), Warned ("The doctor warned that the situation was serious"), Confirmed ("The manager confirmed that the position was available"), Denied ("He denied having any involvement"), Argued ("She argued that the policy was unfair"), Acknowledged ("He acknowledged that improvements were needed"), Revealed ("The report revealed that costs had doubled"). Write each as a reported speech sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Tense Backshift in Reported Speech', description: 'When reporting what someone said, tenses shift back in time: Direct: "I am happy." Reported: She said she WAS happy. Direct: "I will call you." Reported: He said he WOULD call me. Direct: "I have finished." Reported: She said she HAD finished. Direct: "I can help." Reported: He said he COULD help. Direct: "I was working." Reported: She said she HAD BEEN working. Convert these 5 sentences to reported speech: 1) "I love this city." (She said...) 2) "We will win." (They believed...) 3) "I have never been abroad." (He admitted...) 4) "I can speak three languages." (She told me...) 5) "I was studying all night." (He explained...)  Write 3 more of your own conversions.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Report a Famous Speech or Movie Dialogue', description: 'Record yourself for 1 minute reporting what a famous person said - a politician, a movie character, a sports star, or a teacher who inspired you. Use varied reporting verbs throughout - not just "said". Example: "Mahatma Gandhi once declared that he would not let anyone walk through his mind with dirty feet. He insisted that... He believed that... He argued that..." This exercise builds both vocabulary and reported speech fluency simultaneously.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 50,
    title: 'Conditionals',
    description: 'Day 50: Just 10 days left! You have come so far - push hard this final stretch and finish like a champion! Conditionals let you talk about possibilities, dreams, regrets, and hypothetical situations. They are essential for interviews, debates, and sophisticated conversations.',
    tasks: [
      { type: 'speaking', title: 'Your Life in Conditionals', description: 'Speak for 2 minutes using conditional sentences to reflect on your life. Use all three types: Type 1 (real future possibility): "If I complete this challenge, I will feel incredibly proud." Type 2 (imaginary present): "If I could speak perfect English right now, I would apply for an international job immediately." Type 3 (past regret): "If I had started learning English five years ago, I would have had so many more opportunities by now." Make every sentence personal and genuine - the most powerful speaking practice comes from real thoughts and real emotions.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Conditional Sentences Explained Simply', description: 'Search YouTube for "conditional sentences English explained simply" and watch a 5-minute video. Write one example sentence for each of the three main conditional types. Notice: Type 1 uses will + present simple. Type 2 uses would + past simple. Type 3 uses would have + past participle. These are the exact conditional patterns tested in IELTS, TOEFL, and every English proficiency exam.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read These Conditional Sentences Aloud', description: 'Read these clearly, feeling the meaning of each one: "If you practice English for just 30 minutes every day, you will be surprised by your progress within a month. If I were the Education Minister, I would make spoken English a daily class from Grade 1. If more Indians had learned English 20 years ago, our software industry would have grown even faster. If you had told me a year ago that I would be speaking confidently in English today, I would not have believed you. Unless we continue practicing after this challenge ends, we will slowly lose what we have gained. Provided that we keep going, the sky is the limit." Read it twice. Which sentence resonates most with you?', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Conditional Expressions - 10 Structures', description: 'Learn these conditional variations beyond basic if: "As long as" ("As long as you keep practicing, you will improve"), "Provided that" ("I will join provided that the salary is right"), "Unless" ("Unless you ask, you will never know"), "Even if" ("Even if it is difficult, I will not give up"), "In case" ("Take an umbrella in case it rains"), "Suppose" ("Suppose you won a million rupees - what would you do?"), "What if" ("What if you could speak to anyone in the world?"), "On condition that" ("I will help on condition that you help me later"), "Assuming that" ("Assuming that all goes well, we will finish by Friday"), "Otherwise" ("Study hard - otherwise you will regret it"). Write each in your own sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Mixed Conditionals - Advanced English', description: 'Mixed conditionals combine different time periods. TYPE 2 + TYPE 3 MIX - imaginary past affecting present: "If I had studied medicine (past), I would be a doctor now (present)." "If he had not moved to Mumbai (past), he would still be working in the village (present)." TYPE 3 + TYPE 2 MIX - past regret affecting hypothetical present: "If I were more confident (present), I would have spoken up in that meeting (past)." Write 4 mixed conditional sentences about your own life - real past situations and how they affect your present, or current traits and how they affected past situations.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Dream Life Speech Using Conditionals', description: 'Record yourself for 1 minute giving a passionate speech about your dream future using conditional sentences. Include: what you will do if you achieve your goals (Type 1), what your life would look like in your ideal world (Type 2), and what you wish you had done differently to be further ahead today (Type 3). This speech combines grammar mastery with genuine personal reflection - the most powerful combination in language learning. Make it count.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
];

const patch = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected');
  for (const d of updates) {
    const totalXP = d.tasks.reduce((s, t) => s + t.xp, 0);
    await Day.updateOne(
      { dayNumber: d.dayNumber },
      { $set: { description: d.description, tasks: d.tasks, totalXP } }
    );
    console.log(`Updated Day ${d.dayNumber}`);
  }
  console.log('Done!');
  await mongoose.connection.close();
  process.exit(0);
};

patch().catch((e) => { console.error(e); process.exit(1); });
