require('dotenv').config();
const mongoose = require('mongoose');
const Day = require('../models/Day');

const updates = [
  {
    dayNumber: 51,
    title: 'Advanced Vocabulary',
    description: 'Day 51: The final 10 days begin! Advanced vocabulary is what separates a good English speaker from an impressive one. Today you will learn words that make people sit up and listen - words that show education, depth, and confidence.',
    tasks: [
      { type: 'speaking', title: 'Speak Using 5 Advanced Words Naturally', description: 'Use these 5 advanced words in a 2-minute speech about any topic you care about: Eloquent, Profound, Resilient, Articulate, Compelling. Example: "One of the most eloquent speakers I have ever heard was my college professor. His lectures were profound - they changed the way I thought about the world. What made him compelling was not just his vocabulary but his ability to make complex ideas feel personal and real." Now use the same 5 words in YOUR OWN speech about someone or something you admire.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Advanced English Vocabulary in Context', description: 'Search YouTube for "advanced English vocabulary in use" or watch any TED talk and pause when you hear a word you do not know. Write 5 advanced words you hear, guess their meaning from context first, then confirm with a dictionary. Learning vocabulary from context - not just word lists - is how advanced speakers build their range. The context tells you not just the meaning but how and when to use the word.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Advanced Paragraph Aloud', description: 'Read with confidence: "The most eloquent communicators are not necessarily those with the largest vocabularies. True linguistic proficiency lies in the judicious use of precise words - selecting the exact term that conveys your intended meaning with clarity and impact. A single well-chosen word can illuminate an idea that a dozen ordinary words cannot adequately express. This is why reading voraciously, listening attentively, and speaking courageously remain the three indispensable pillars of advanced English acquisition. Vocabulary is not memorized - it is absorbed, tested, refined, and ultimately owned." Read it twice. Identify 5 advanced words and their meanings.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Advanced Vocabulary - 10 Powerful Words', description: 'Learn with examples: Eloquent ("She gave an eloquent speech that moved the entire audience"), Resilient ("Indians are incredibly resilient in the face of adversity"), Pragmatic ("We need a pragmatic solution, not an idealistic one"), Diligent ("Only the most diligent students reach the top"), Meticulous ("She is meticulous about checking every detail"), Profound ("Reading changed my life in a profound way"), Ambiguous ("His answer was ambiguous - I could not tell what he meant"), Lucid ("Her explanation was lucid and easy to follow"), Tenacious ("She was tenacious - she never stopped trying"), Exemplary ("His work ethic is exemplary"). Write each in a sentence about a real person you know.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Advanced Sentence Formation - Inversion for Emphasis', description: 'Advanced English speakers use inversion for dramatic emphasis. Normal: "I have never seen such dedication." Inverted: "Never have I seen such dedication." Normal: "I only realized the truth later." Inverted: "Only later did I realize the truth." Normal: "He not only passed but scored highest." Inverted: "Not only did he pass, but he scored highest." Common inversion starters: Never, Only, Not only, Rarely, Seldom, Little, Hardly. Write 5 inverted sentences about your own experiences. This grammar pattern immediately sounds sophisticated and is highly valued in IELTS writing band 8 and above.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Motivational Speech With Advanced Vocabulary', description: 'Record a 1-minute motivational speech to someone who has just started learning English and feels like giving up. Use at least 6 advanced vocabulary words naturally. Do not force them - use them only where they genuinely fit. Start: "The journey you have chosen is not an easy one, but it is profoundly worthwhile..." Your speech should inspire, educate, and demonstrate the exact level of English they are working toward.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 52,
    title: 'Public Speaking',
    description: 'Day 52: Public speaking is the number one fear of most people - more feared than death itself. But it is also the skill most rewarded in every career. Today you will face that fear directly and discover something important: the more you do it, the less scary it becomes.',
    tasks: [
      { type: 'speaking', title: 'Give a 2-Minute Speech on a Topic You Know', description: 'Choose ONE topic you genuinely know well - your field of work, your hometown, a skill you have, or your experience with this challenge. Structure it: Hook (15 sec) - start with a surprising fact or question. Body (90 sec) - 3 points with one example each. Close (15 sec) - end with something memorable. The key rule of public speaking: do not try to say everything. Say three things very well. Stand up while recording - your energy and posture change everything.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: A TED Talk Opening and Closing', description: 'Search YouTube for "best TED talk openings" or any TED talk and focus ONLY on the first 60 seconds and last 60 seconds. Write: exactly how they open (story, question, or shocking statement?) and exactly how they close (callback to opening, call to action, or powerful final line?). The opening and closing are the only parts an audience always remembers. Everything else is the middle.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Famous Speech Opening Aloud', description: 'Read with power and pauses: "I have a dream that one day this nation will rise up and live out the true meaning of its creed. I have a dream that one day on the red hills of Georgia, the sons of former slaves and the sons of former slave owners will be able to sit down together at the table of brotherhood. I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character. I have a dream today!" Read it three times - each time with more power. Notice the repetition of "I have a dream" - this technique is called anaphora, and it is one of the most powerful tools in public speaking.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Public Speaking Vocabulary - 10 Words', description: 'Learn: Enunciate ("Enunciate clearly so every word is heard"), Cadence ("His speech had a beautiful rhythmic cadence"), Poise ("She spoke with remarkable poise and confidence"), Rhetoric ("His rhetoric was powerful but lacked substance"), Empathize ("A great speaker empathizes with the audience"), Modulate ("Modulate your voice to emphasize key points"), Captivate ("She captivated the audience from the first sentence"), Persuade ("The best speeches persuade through emotion and logic"), Conviction ("Speak with conviction even if you feel nervous"), Resonate ("Her words resonated deeply with everyone in the room"). Write each in a public speaking context sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Rhetorical Questions - Speaking Technique + Grammar', description: 'Rhetorical questions are asked for effect, not for an answer. They engage audiences and emphasize points. Examples: "Is it not time that we took English seriously?" "Have we not all felt the pain of not being understood?" "What would happen if every Indian spoke fluent English?" "Who among us has not dreamed of a better future?" Pattern: usually negative question or what/who/how question. Write 5 rhetorical questions about a topic you care about - education, technology, the environment, or this English challenge. Then write a 3-sentence response to each as if you are answering yourself.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Camera Speaking Challenge - Full Eye Contact', description: 'Record a 1-minute speech looking DIRECTLY at the camera the entire time. No looking away, no looking down at notes. Topic: "One thing I know now about English that I wish I had known on Day 1." Stand up, speak with energy, and maintain eye contact with the camera the entire time. After recording, watch it back. Did you look confident? This is the exercise that separates people who learn English from people who use it.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 53,
    title: 'Confidence Building',
    description: 'Day 53: Eight days left. Confidence is not something you have before you speak - it is something you build by speaking. Every recording you have made, every task you have completed, every day you showed up has been building this. Today you claim it.',
    tasks: [
      { type: 'speaking', title: 'Speak Your Affirmations Aloud in English', description: 'Speak these affirmations aloud with full conviction - not quietly, but powerfully as if you truly believe each one: "I am a confident English speaker." "I express my ideas clearly and naturally." "I learn from my mistakes and I keep going." "Every day my English gets stronger." "I am proud of how far I have come." "I deserve to be heard." Now create 5 of your own affirmations about your specific English goals. The science is clear: saying positive statements aloud repeatedly builds the neural pathways that make them true.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: English Confidence Tips', description: 'Search YouTube for "how to speak English confidently without fear" and watch one video. Write 3 specific techniques for building speaking confidence. Look for tips like: accept that mistakes are part of the process, focus on communication not perfection, prepare your first sentence before speaking, slow down your speech rate, and breathe before you begin. Which 3 tips resonate most with your personal experience?', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Confidence Paragraph Aloud as if You Wrote It', description: 'Read this as your own truth: "Fifty-three days ago, I made a decision. I decided that I was done being the person who understood English but could not speak it. I was done nodding in conversations I only half understood. I was done letting opportunities pass because I was afraid of making mistakes. Every single day since then, I have shown up. Some days it was hard. Some days I wanted to skip. But I did not. And today, on Day 53, I can hear the difference. My voice is steadier. My sentences are longer. My fear is smaller. I am not finished yet. But I am no longer who I was. And that is everything." Read it twice. The second time, make every word feel personal and true.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Confidence and Self-Belief - 10 Words', description: 'Learn: Assertive ("Be assertive - state your opinion clearly and calmly"), Poised ("She walked into the interview poised and ready"), Self-assured ("He answered every question in a self-assured manner"), Composed ("Even under pressure, she remained completely composed"), Empowered ("Learning English made me feel truly empowered"), Courageous ("Speaking a foreign language requires real courage"), Unwavering ("Her commitment to improving was unwavering"), Radiate ("Confident people radiate positivity"), Exude ("She exudes confidence in every situation"), Indomitable ("The human spirit is truly indomitable"). Write each in a sentence about your own confidence journey.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Positive Affirmation Sentence Structures', description: 'Affirmations use specific grammar patterns to be most effective: Present simple (stating a current truth): "I speak English confidently." Present continuous (an action in progress): "I am becoming more fluent every day." Present perfect (acknowledging progress): "I have come so far in 53 days." Future with will (commitment): "I will continue improving after this challenge." Should + be (advice to yourself): "I should be proud of what I have achieved." Write 2 sentences for each of these 5 structures as personal affirmations. Read them all aloud. This is the grammar of self-belief.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Mirror Speaking Practice', description: 'Stand in front of a mirror. Record yourself speaking for 1 minute on this topic: "The person I was when I started Day 1 vs the person I am today on Day 53." Look at yourself in the mirror while speaking. Notice your posture, your facial expressions, your eye contact. Speak to yourself as you would speak to someone you are trying to inspire. This is the most powerful confidence exercise: seeing yourself as the capable, improving English speaker you have become.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 54,
    title: 'Real Conversations',
    description: 'Day 54: All the grammar, vocabulary, and practice in the world means nothing until it happens in a real conversation. Today is about taking everything you have learned off the page and into actual human interaction - the ultimate test and the ultimate reward.',
    tasks: [
      { type: 'speaking', title: 'Simulate a Real Conversation', description: 'Speak for 2 minutes simulating a real conversation with someone. Pick a scenario: meeting a new colleague, catching up with an old friend, or chatting with a neighbor. Play BOTH roles. Switch between the two people naturally. Use casual, real language - contractions, filler words, questions, reactions. Example: "Hey! I have not seen you in ages! How have you been? Oh I have been really busy actually - I just started a new job. No way! That is amazing - where? Well it is at this tech company in..." The goal is to sound like a real conversation, not a rehearsed speech.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Real Unscripted English Conversations', description: 'Search YouTube for "real English conversation unscripted" or "natural English conversation practice" and watch a 5-minute video of people actually talking - not a lesson. Notice: how often they interrupt each other, how they use "mmm", "yeah", "right", "I see" to show they are listening, how conversations change direction unexpectedly, and how they use humor. Real conversation English is very different from textbook English - and today you study the real thing.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Casual Conversation Aloud Naturally', description: 'Read this as naturally as possible - not like a textbook, but like a real conversation: "A: So how is the new place? B: Oh, honestly? It is amazing. I cannot believe I waited so long to move. A: Really? I remember you were so stressed about it. B: I know! I was convinced it would be a disaster. But actually, the landlord is great, the neighbors are quiet - A: And the commute? B: That is the only thing - it is a bit long. About 45 minutes each way. A: Ugh, that is rough. B: Yeah but honestly? I put on a podcast and it flies by. I have actually started looking forward to it. A: That is a very healthy attitude. B: Ha - either that or I have completely lost it." Read it twice at natural speed.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Conversation Fillers and Real Talk - 10 Phrases', description: 'Learn these as complete phrases used in real conversation: "To be honest with you" (introducing a candid opinion), "If I am being completely transparent" (sharing something genuine), "You know what I mean?" (checking understanding), "That is a really good point" (acknowledging what someone said), "I had not thought of it that way" (showing you are listening), "Now that you mention it" (a new idea sparked by their words), "I totally get where you are coming from" (showing empathy), "Long story short" (about to summarize), "At the end of the day" (the final conclusion), "Do not even get me started on" (passionate about a topic). Use 5 of these in today\'s confidence recording.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Ellipsis and Reduction - How Real Conversation Works', description: 'In real conversation, people drop words that are understood from context. This is called ellipsis. Full: "Are you going to the party tonight?" Real: "Going to the party tonight?" Full: "I will see you tomorrow." Real: "See you tomorrow." Full: "Have you eaten yet?" Real: "Eaten yet?" Full: "Do you want some tea?" Real: "Want some tea?" Full: "I am not sure about that." Real: "Not sure about that." This is NOT bad grammar - it is natural spoken grammar. Write 5 examples of full sentences and their natural short versions. Then practice saying the short versions - they should feel like normal speech.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Have a Real English Conversation Today', description: 'This is the most important task of Day 54. Have an actual English conversation with a real person - a friend, family member, colleague, or anyone willing. It can be 2 minutes or 20. Then record a 1-minute reflection immediately after: How did it feel? What went well? What was hard? What surprised you? If no one is available, call someone and challenge them to speak English with you for 2 minutes. Real conversation is the finish line this entire journey has been leading toward.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 55,
    title: 'Mock Interviews',
    description: 'Day 55: Five days left - the final push! If there is one skill that can immediately change your life circumstances, it is performing well in an English job interview. Today we simulate the real thing from start to finish.',
    tasks: [
      { type: 'speaking', title: 'Answer 5 Real HR Interview Questions', description: 'Answer each question in 30-40 seconds - be specific, not generic: 1) "Tell me about yourself." 2) "Why do you want to work here?" 3) "What is your biggest weakness and how are you working on it?" 4) "Describe a situation where you showed leadership." 5) "Where do you see yourself in 3 years?" For each answer: avoid generic phrases like "I am hardworking and dedicated" - everyone says this. Use specific examples, real numbers, and genuine stories. The interviewer remembers specifics, not generalities.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: How to Answer Tough Interview Questions', description: 'Search YouTube for "how to answer tough interview questions in English" and watch one video. Write: the answer structure suggested for "Tell me about yourself" (most videos recommend past + present + future), the best way to answer "What is your weakness?" (name a real weakness, then explain how you are actively improving it), and 2 phrases to use when you need a moment to think ("That is a great question, let me think for a moment", "Could I take just a second to organize my thoughts?").', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read These Model Interview Answers Aloud', description: 'Read with full professional confidence: "Tell me about yourself: I am a software developer with three years of experience building mobile applications. I completed my engineering degree from Pune University and immediately joined a startup where I worked on products used by over 50,000 people. I am particularly passionate about user experience design and I have been learning advanced UI skills in my spare time. I am excited about this role because your company is doing exactly the kind of work I want to be part of. Why do you want this role: I have followed your company for two years and I genuinely believe in what you are building. The problems you are solving are ones I think about every day. I want to be part of a team that is making a real difference, not just writing code for its own sake." Read both answers twice with confidence.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Interview Power Words - 10 Words', description: 'Learn these words that impress interviewers: Initiative ("I took the initiative to restructure our entire filing system"), Spearheaded ("I spearheaded the new customer feedback program"), Streamlined ("I streamlined the reporting process saving 5 hours per week"), Collaborated ("I collaborated with cross-functional teams on three major projects"), Delivered ("I consistently delivered projects ahead of schedule"), Exceeded ("I exceeded my sales targets by 30% last quarter"), Implemented ("I implemented a new training system for junior staff"), Mentored ("I mentored two junior developers over the past year"), Optimized ("I optimized the app performance reducing load time by 40%"), Championed ("I championed the idea of flexible work hours for our team"). Write each in a sentence about a real achievement of yours.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'STAR Method Grammar - How to Structure Interview Stories', description: 'The STAR method gives your interview answers perfect structure: S - Situation (simple past): "When I was working at my previous company..." T - Task (past continuous or simple past): "I was responsible for managing the social media accounts..." A - Action (simple past, focus on I not we): "I decided to redesign the entire content calendar. I introduced weekly analytics reviews. I began testing different posting times..." R - Result (simple past + numbers): "As a result, engagement increased by 45% in 3 months." Write a complete STAR answer about any challenge you faced at work, college, or in a personal project. Practice until it flows naturally in under 90 seconds.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Full Mock Interview Recording', description: 'Record a complete 2-minute mock interview. Sit straight, dress presentably if possible, look at the camera. Answer these back to back as if in a real interview: "Tell me about yourself" (40 sec), "What is your greatest achievement?" (40 sec), "Why should we hire you?" (40 sec). Watch yourself back and rate: Did I sound confident? Did I use specific examples? Was my grammar mostly correct? Did I make eye contact with the camera? Record again and aim to improve every single point. This recording could literally be practice for the interview that changes your life.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 56,
    title: 'Group Discussion',
    description: 'Day 56: Group Discussions are used by top companies and colleges to filter candidates. They test your confidence, communication, listening, and leadership simultaneously in 10 minutes. Today you will master the art of contributing powerfully without dominating.',
    tasks: [
      { type: 'speaking', title: 'Share Your Opinion on a GD Topic', description: 'Speak for 2 minutes on this common GD topic as if you are in a real group: "Should social media platforms be regulated by the government?" Take a clear position, support it with 2-3 specific reasons and examples, acknowledge one counter-argument, and conclude strongly. Use GD language: "I strongly believe that...", "The evidence suggests...", "While some argue that... I would counter that...", "To conclude my point...", "I would like to add to what was said earlier..." Speak with conviction, clarity, and control.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Group Discussion Tips and Examples', description: 'Search YouTube for "group discussion tips for freshers" or "GD round tips campus placement English" and watch one video. Write: 3 do\'s in a GD (maintain eye contact with all participants, build on others\' points, use data when possible), 3 don\'ts (never interrupt aggressively, never dominate and prevent others from speaking, never stay silent for the entire discussion), and 2 phrases to use when entering the discussion ("I would like to add a point here" and "Building on what was just said...").', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read These GD Contribution Phrases Aloud', description: 'Read each phrase clearly and practice it until it sounds natural: Opening: "I would like to start by saying that this is a critically important issue." Agreeing: "I completely agree with that perspective and would like to add..." Disagreeing politely: "I respect that viewpoint, however I believe the evidence suggests otherwise..." Adding information: "Furthermore, we should also consider that..." Bringing someone in: "I noticed you had a point to make - please go ahead." Summarizing: "To bring together the key points made in this discussion..." Concluding your turn: "So to summarize my position on this matter..." Practice all 7 phrases until they feel like second nature.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Group Discussion Language - 10 Phrases', description: 'Learn as complete usable expressions: "The crux of this issue is" (the most important point), "I would like to draw your attention to" (pointing out something important), "This is a double-edged sword" (something with both good and bad effects), "We must look at the bigger picture" (consider the wider context), "The data is unequivocal" (the evidence is absolutely clear), "I beg to differ" (polite disagreement), "That is a valid concern, however" (acknowledge then counter), "In the interest of balance" (presenting both sides), "This merits serious consideration" (this is worth thinking about carefully), "Let us not lose sight of the fact that" (reminding the group of something important). Write 5 of these in GD context sentences.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Hedging Language - Sound Thoughtful Not Aggressive', description: 'In GDs, sounding thoughtful and balanced is more impressive than sounding aggressive. Hedging language softens strong claims: Instead of "This is wrong" say "This may not be entirely accurate." Instead of "Everyone knows" say "Many would argue that." Instead of "This will definitely" say "This is likely to." Instead of "The fact is" say "Evidence suggests that." Instead of "Obviously" say "It appears that." Aggressive language loses GDs. Measured, evidence-based language wins them. Rewrite these aggressive GD statements using hedging: 1) "Social media is obviously destroying society." 2) "Everyone knows the government is corrupt." 3) "This policy will definitely fail." 4) "It is a proven fact that online learning is worse." Write 4 of your own hedged opinion sentences on any topic.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Simulate a GD by Yourself', description: 'Record yourself for 1 minute simulating a group discussion on this topic: "Is cricket given too much attention in India compared to other sports?" Play 3 different participants with different opinions. Switch between them, interrupt politely, agree, disagree, and summarize at the end. Yes, this feels strange doing alone - but it forces you to think from multiple perspectives simultaneously, which is exactly what GD requires. This exercise builds the mental agility that makes you stand out in real GDs.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 57,
    title: 'Debate Practice',
    description: 'Day 57: Three days left! Debate is the ultimate test of English - you must think, listen, and speak simultaneously under pressure. The skills you build today - arguing clearly, countering respectfully, persuading powerfully - will serve you in every conversation for the rest of your life.',
    tasks: [
      { type: 'speaking', title: 'Argue Both Sides of a Debate Topic', description: 'Speak for 2 minutes total - 1 minute FOR and 1 minute AGAINST this topic: "Online education is better than classroom education." FOR (1 min): Give your 3 strongest arguments with specific examples. AGAINST (1 min): Demolish your own arguments with equally strong counter-points. This exercise is not about what you personally believe - it is about training your mind to see all sides of an argument and articulate them powerfully. The best debaters and the best professionals can argue any position convincingly.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: English Debate Competition', description: 'Search YouTube for "English debate competition students" and watch one 5-minute clip of a real student debate. Notice: How do they open their argument? How do they use evidence? How do they rebut the other side? How do they manage time? How do they handle nerves? Write 3 techniques you observed that you want to incorporate into your own speaking. Real debate competitions show you the standard to aim for.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read These Debate Arguments Aloud With Conviction', description: 'Read the FOR side, then the AGAINST side, with full commitment to each: FOR technology in education: "Technology has democratized education in a way that was unimaginable 20 years ago. A child in rural Jharkhand today can access the same YouTube lectures as a student at Delhi University. The Khan Academy alone has delivered over 2 billion lessons globally for free. To argue against technology in education is to argue against equality itself." AGAINST: "Yet for every success story, there are millions of students staring at blank screens in areas with no WiFi, no device, and no family member who can help when the technology fails. A motivated teacher in a real classroom does something no algorithm can - she sees the child who is struggling and stops the lesson to help them." Read each side twice with genuine conviction.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Debate Language - 10 Powerful Expressions', description: 'Learn: "The evidence overwhelmingly suggests" (strong factual claim), "My opponent\'s argument, while interesting, fails to account for" (respectful rebuttal), "This point is fundamentally flawed because" (strong counter), "Let me present three concrete examples" (structured argument), "The real question we should be asking is" (reframing the debate), "This argument does not hold up under scrutiny" (challenging weak logic), "I challenge the premise of that argument" (questioning the assumption), "The statistics speak for themselves" (using data), "Far from being a solution, this would exacerbate the problem" (showing a policy makes things worse), "History has consistently demonstrated that" (using historical evidence). Write 5 of these in debate sentences on any topic.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Concession and Counter - The Most Powerful Debate Structure', description: 'The most persuasive debaters acknowledge the other side before defeating it. This is called concession + counter. Structure: "While it is true that [acknowledge their point], the reality is that [your stronger point]." Examples: "While it is true that social media connects people, the reality is that it has also created unprecedented levels of anxiety among teenagers." "Although I acknowledge that uniforms reduce inequality in dress, they do nothing to address the deeper inequalities in education quality." "Granted that electric cars are more expensive initially, they save significantly more over a 5-year period." Write 5 concession + counter sentences on topics you care about. This structure alone will make your English debates and discussions dramatically more sophisticated.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Record Your Strongest 1-Minute Argument', description: 'Record your most powerful 1-minute argument on any topic you feel strongly about - education, environment, technology, sports, or this English journey. Structure it: 1 strong opening statement, 2 specific supporting points with evidence or examples, 1 counter-argument acknowledged and defeated, 1 powerful closing line. This is your chance to show everything you have learned about speaking in this 57-day journey. Make it count. Make it yours. Make it unforgettable.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 58,
    title: 'Final Review',
    description: 'Day 58: Two days from the finish line. Today is not about learning anything new - it is about consolidating everything you have built over 57 incredible days. You are reviewing not just English but yourself.',
    tasks: [
      { type: 'speaking', title: 'Compare Day 1 You vs Day 58 You', description: 'Speak for 2 minutes answering this: "How has your English changed since Day 1?" Be specific - not just "it is better." Think about: Can you speak longer without stopping? Do you know more vocabulary? Are you less afraid? Do you understand more when you listen? Can you write more professionally? Has anyone commented on your improvement? Use before and after comparisons: "On Day 1 I could not... but now I can...", "I used to struggle with... but these days...", "The biggest change I notice is..." This reflection is as important as any grammar exercise.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Listen to One of Your Earlier Recordings', description: 'Go back and listen to a recording you made in the first two weeks of this challenge. Listen carefully without cringing - be an objective observer. Write: 3 specific things that have improved (speed, vocabulary, confidence, pronunciation), 1 area you still want to work on, and 1 thing you are genuinely proud of. Hearing your own progress is the most powerful motivator in any learning journey. Most learners never do this - do not be most learners.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read Your Favorite Passage From This Journey', description: 'Go back through the days and find the reading task that moved you most - the one that felt personal, powerful, or particularly beautiful. Read it aloud today with everything you have learned. Notice how differently it sounds now compared to when you first read it. Your pronunciation is clearer, your rhythm is more natural, your confidence is stronger. Then read this final sentence slowly: "You have shown up every single day for 58 days. That is not luck. That is character." Read it one more time.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Revise Your 10 Favorite Words From This Journey', description: 'Look back through the vocabulary tasks from the last 57 days and choose the 10 words that resonated most with you - the ones you have actually used, the ones you found beautiful, or the ones that finally clicked. Write each word, its meaning, and a new example sentence you create today - not the one from the lesson. These are YOUR words now. A vocabulary word you have chosen, used, and revisited three times is yours forever.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Self-Correction Practice - Find Your Patterns', description: 'Write 10 sentences freely about anything you want. Then go back and check each one: Is the tense correct? Are articles right? Are prepositions correct? Is subject-verb agreement right? Are there any words missing? Correct any errors you find. This is called self-editing - one of the most important skills in advanced English. Professional writers, journalists, and language learners all do this. The ability to identify and correct your own errors means you are not dependent on a teacher. You are your own teacher now.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Speak Freely for 1 Full Minute Without Stopping', description: 'Record yourself speaking for exactly 1 minute on anything - your day, your feelings, your plans, your dreams, a memory, a opinion. No preparation. No notes. No stopping. Just speak. This is the purest test of fluency: unfiltered, unprepared, unedited English flowing from your mind through your mouth. On Day 1 this felt impossible. Today it is not. Listen back and notice: you have earned this.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 59,
    title: 'Celebration Day',
    description: 'Day 59: One day from the finish line! Today we celebrate what you have built - not just English skills but the discipline, courage, and consistency that brought you here. Most people who started this challenge are not reading this right now. You are. That means everything.',
    tasks: [
      { type: 'speaking', title: 'Speak Proudly About Your 59-Day Journey', description: 'Speak for 2 minutes as if you are sharing your story with someone who is considering starting this challenge. Tell them: Why did you start? What was the hardest moment? What surprised you the most? What is the single most valuable thing you learned? Would you recommend it? Make your story compelling - because it genuinely is. You did something most people never do. Speak about it with the pride it deserves.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: A Motivational Speech About Perseverance', description: 'Search YouTube for "motivational speech perseverance English" and watch one that genuinely moves you. Write 3 lines from the speech that hit you personally. Note the speaking techniques used - the pauses, the vocal changes, the personal stories. You have spent 59 days learning English. Now you can understand and feel inspired by a speech in this language. That is remarkable. That is the point of all of this.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read These Motivational Quotes Aloud With Emotion', description: 'Read each quote slowly, then pause and let it land before moving to the next: "The secret of getting ahead is getting started." - Mark Twain. "It does not matter how slowly you go, as long as you do not stop." - Confucius. "Fluency comes from consistency, not perfection." - Every Day Better. "You did not come this far only to come this far." - Unknown. "The person who says they cannot and the person who says they can are both right." - Henry Ford. "Speak even if your voice shakes. That is courage." - Unknown. "You are not the same person who started Day 1. Prove it on Day 60." - Every Day Better. Read them all twice. Choose your favorite and write it down somewhere you will see it every day.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Words That Describe What You Have Become', description: 'These words describe you today - learn them and own them: Perseverant ("A perseverant learner keeps going when others stop"), Dedicated ("She was dedicated to improvement every single day"), Accomplished ("He felt accomplished after completing the challenge"), Transformed ("The 60-day journey was truly transformational"), Resilient ("Resilient people turn obstacles into stepping stones"), Consistent ("Consistent effort always beats occasional brilliance"), Courageous ("It takes courage to speak a new language every day"), Disciplined ("Disciplined practice creates lasting results"), Evolved ("She had genuinely evolved as a communicator"), Unstoppable ("Once you decide you are unstoppable, you become it"). Write each in a sentence about YOUR journey.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Write Your Achievement Summary - All Tenses', description: 'Write a paragraph about your 59-day journey using all the tenses you have mastered. Include: simple past (what you did), present perfect (what you have achieved), present continuous (what you are still working on), future simple (what you will do next). Example structure: "59 days ago I started this challenge because... (past). Over these weeks I have learned... (present perfect). Right now I am still working on... (present continuous). After Day 60 I will... (future). By the end of this year I will have... (future perfect)." Write your genuine, personal version. This paragraph is proof of everything.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Write a Thank You to Yourself', description: 'Record a genuine 1-minute message thanking yourself for not giving up. Talk directly to yourself as if you are speaking to your best friend. Acknowledge the days it was hard. Acknowledge the days you almost skipped. Acknowledge the growth. Use everything you have learned - the vocabulary, the connectors, the tenses, the confidence. End with one promise to yourself about continuing after Day 60. This recording is for you. No one else has to hear it. But you will remember it.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 60,
    title: 'Champion Day',
    description: 'Day 60: YOU DID IT! 60 days of English practice complete. You are not the same person who started Day 1. You showed up every single day. You spoke when it felt uncomfortable. You kept going when it was hard. Today we do not learn new things - today we celebrate and prove what we have become.',
    tasks: [
      { type: 'speaking', title: 'Your Champion Speech - 2 Full Minutes', description: 'This is the most important speaking task of the entire 60 days. Speak for 2 full minutes about your complete transformation. Cover: Who were you on Day 1 in terms of English? What was your biggest fear? What was your proudest moment in these 60 days? How has your English specifically changed? What will you do with this English now? How do you feel right now, in this moment, having completed what most people never finish? Speak from the heart. Use every skill you have built. This speech is the proof.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Listen to Your Day 1 Recording and Your Most Recent Recording', description: 'Find your very first confidence recording from Day 1. Listen to it. Then immediately listen to your most recent recording. Write what you hear: What has changed in your pronunciation? In your vocabulary? In your confidence? In your fluency? In your speed? The difference between those two recordings is 60 days of consistent effort. That difference is you. That difference is real. That difference is permanent. Write at least 5 specific improvements you can hear.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read Your Favorite Paragraph From the Entire Journey', description: 'Go back through all 60 days and find the single paragraph that meant the most to you. The one that moved you, challenged you, or described exactly how you felt. Read it aloud one final time with everything you have. Then read this: "You started this because you believed something better was possible for you. You were right. English did not just give you a language. It gave you access. Access to ideas, opportunities, people, and versions of yourself that were waiting behind a language barrier. That barrier is gone now. What you do next is entirely up to you. And that is exactly as it should be." Read it slowly. Read it twice.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'The Final 10 Words - Words for Champions', description: 'Your final vocabulary list - words that belong to people who finish what they start: Mastery ("Mastery is not perfection - it is relentless improvement"), Legacy ("What legacy will your English skills create?"), Transcend ("You have transcended the limitations you started with"), Flourish ("Watch your confidence flourish in the months ahead"), Pinnacle ("Completing 60 days is your personal pinnacle of discipline"), Triumph ("This is a genuine triumph of consistency over comfort"), Perpetual ("Make perpetual improvement your permanent habit"), Inimitable ("Your journey is inimitable - it belongs only to you"), Luminous ("Your future is luminous - go and light it up"), Champion ("A champion is simply someone who refused to give up"). Write each in a sentence about your future - where you are going from here.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Future Perfect - What You Will Have Achieved', description: 'The future perfect tense describes actions that will be completed by a future point. It is the tense of achievement: "By the end of this year, I will have spoken English every single day for 6 months." "By the time I attend my next job interview, I will have practiced for over 60 hours." "By next Diwali, I will have read 10 English books." "In five years, I will have built a life where English is as natural as breathing." Write 5 future perfect sentences about what YOU will have achieved with your English in the next year. These are not wishes - they are plans. The grammar of your future.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Your Final Transformation Video', description: 'Record your final video. Speak for 1-2 minutes. No script. No preparation. Just you, your English, and your truth. Tell the world - or just yourself - what these 60 days meant. What you learned about English. What you learned about yourself. What you are going to do next. Speak with the voice of someone who has earned the right to be heard - because you have. This recording is your proof. Your certificate. Your trophy. Keep it. Watch it on the days you doubt yourself. You did this. You are Every Day Better.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
];

const patch = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected');
  for (const d of updates) {
    const totalXP = d.tasks.reduce((s, t) => s + t.xp, 0);
    await Day.updateOne(
      { dayNumber: d.dayNumber },
      { $set: { description: d.description, tasks: d.tasks, totalXP } }
    );
    console.log(`Updated Day ${d.dayNumber}`);
  }
  console.log('Done!');
  await mongoose.connection.close();
  process.exit(0);
};

patch().catch((e) => { console.error(e); process.exit(1); });
