require('dotenv').config();
const mongoose = require('mongoose');
const Day = require('../models/Day');

const updates = [
  {
    dayNumber: 21,
    title: 'Education & Learning',
    description: 'Day 21: Three weeks done - incredible consistency! Education is the topic that appears in every English exam, interview, and conversation. Today you will speak about studies, share opinions on learning, and use future tense to talk about your career dreams.',
    tasks: [
      { type: 'speaking', title: 'Talk About Your Education Journey', description: 'Speak for 2 minutes about your education. Cover: Where did you study? What was your favorite subject and why? Who was your most inspiring teacher? What was the hardest exam you faced? What do you wish the education system did differently? Use "I studied...", "My favorite subject was... because...", "I believe education should..."', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Study Motivation in English', description: 'Search YouTube for "study motivation speech English" or "how to study effectively English" and watch one video. Write 3 study tips you heard. Notice how they use future tense: "If you study daily, you will succeed." "You are going to achieve great things." These motivational patterns are very useful in conversations.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Education Paragraph Aloud', description: 'Read clearly: "Education is not just about passing exams - it is about developing the ability to think, question, and grow. The most successful people in the world were not always the best students in class. They were curious. They asked questions. They failed and tried again. In India today, millions of young people are proving that education is the most powerful tool for changing your life. If you are reading this and learning English right now - you are already one of them." Read it twice with pride.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Education - 10 Words', description: 'Learn: Curriculum ("The curriculum needs to include life skills"), Scholarship ("She won a scholarship to study abroad"), Internship ("I did a 3-month internship at a tech company"), Dissertation ("His dissertation was on climate change"), Peer ("I learned a lot from my peers"), Semester ("This semester I am studying economics"), Tutorial ("The online tutorial helped me understand algebra"), Mentor ("My teacher became my mentor"), Academic ("She has an impressive academic record"), Literacy ("Digital literacy is essential today"). Write each in your own sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Future Tense - Will vs Going To', description: 'Two future forms with different meanings: WILL - spontaneous decisions and predictions: "I will study harder this year." "I think English will open many doors for me." GOING TO - planned intentions: "I am going to finish this course by December." "She is going to apply for a scholarship." Write 3 sentences with will and 3 with going to about your education or career plans.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Give Study Advice to a Junior Student', description: 'Record yourself for 1 minute giving genuine study advice to someone one year behind you. What do you wish someone had told you? Be specific - not just "study hard" but HOW. Use: "The one thing I wish I had done earlier is...", "The biggest mistake students make is...", "My top tip is..."', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 22,
    title: 'Friends & Social Life',
    description: 'Day 22: Friendships are built on good communication. The way you talk to friends in English is very different from formal English - it is warmer, faster, funnier. Today you will learn casual conversational English that makes you likeable and easy to talk to.',
    tasks: [
      { type: 'speaking', title: 'Talk About Your Best Friend', description: 'Speak for 2 minutes about your best friend as if introducing them to someone new. Cover: How did you meet? What makes them special? What is your funniest memory together? How have they helped you? Use warm, casual language: "We have been friends since...", "The thing I love most about them is...", "I will never forget the time when..."', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Casual English Conversations Between Friends', description: 'Search YouTube for "casual English conversation between friends" and watch one video. Notice: the speed, the contractions (gonna, wanna, kinda), the filler words (well, like, you know, actually). Write 5 casual phrases friends use. Understanding casual English is just as important as formal English.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Friendship Dialogue Aloud', description: 'Read naturally and casually: "A: Hey! Long time no see! How have you been? B: I know, it has been ages! I have been super busy with work. A: Same here. We really need to catch up properly. B: Absolutely. Are you free this weekend? A: Saturday works for me. We could grab coffee at that new place near the station. B: Perfect! I will send you the location. A: Great - cannot wait! It feels like forever since we just sat and talked." Read it twice like you are really talking to a friend.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Friendship & Social - 10 Words', description: 'Learn: Bond ("We share a strong bond built over years"), Trustworthy ("A good friend must be trustworthy"), Companion ("He has been my companion through every difficulty"), Supportive ("My friends are incredibly supportive"), Genuine ("She is the most genuine person I know"), Loyal ("Loyal friends are rare and precious"), Outgoing ("He is very outgoing and makes friends easily"), Introvert ("As an introvert, I prefer small gatherings"), Empathy ("True friendship requires empathy"), Reconcile ("They had a fight but quickly reconciled"). Write each about a real person in your life.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Past Simple vs Past Continuous - Telling Stories', description: 'When telling stories about friends, we combine two past tenses: Past continuous sets the scene: "We were sitting in the park..." Past simple shows the sudden action: "...when suddenly it started raining!" More examples: "I was walking to class when I bumped into my old friend." "We were laughing so hard that the teacher asked us to leave." Write 4 short story sentences using was/were + ing... when + simple past.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Call a Friend in English Today', description: 'The real challenge: speak to an actual friend or family member in English for at least 2 minutes today. If nobody is available, record an imaginary phone call: "Hey! How are you? I was just thinking about you..." After the call, record a 30-second reflection: How did it go? What was easy? What was difficult?', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 23,
    title: 'Festivals & Culture',
    description: 'Day 23: India is the land of festivals - we celebrate more than any other country in the world! Today you will learn to explain Indian culture and festivals to anyone in the world in confident, beautiful English. This is a topic where you are already the expert.',
    tasks: [
      { type: 'speaking', title: 'Describe Your Favorite Festival', description: 'Speak for 2 minutes about your favorite Indian festival as if explaining it to a foreign friend who has never heard of it. Cover: What is the festival? Why is it celebrated? What do people do? What food is prepared? What is your favorite memory of this festival? Make them WANT to experience it!', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Indian Festivals Explained in English', description: 'Search YouTube for "Diwali explained in English" or "Holi festival English" and watch a 5-minute video. Notice how they explain cultural concepts to non-Indians. Write 3 phrases they use to describe traditions. This is exactly the skill you need for interviews that ask "Tell us about your culture."', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Festival Paragraph Aloud', description: 'Read with warmth and pride: "Diwali is not just a festival of lights - it is a celebration of hope over despair, knowledge over ignorance, and good over evil. Every year, millions of Indian families clean their homes, wear new clothes, prepare sweets, and light thousands of diyas. The night sky fills with fireworks and laughter. Children burst crackers, elders offer prayers, and the whole neighborhood smells of mithai and marigolds. For one magical night, every window in India glows. If you have never experienced Diwali, you have missed one of the most beautiful nights on earth." Read it twice with feeling.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Festivals & Culture - 10 Words', description: 'Learn: Heritage ("The Taj Mahal is part of our cultural heritage"), Ritual ("Lighting diyas is a Diwali ritual"), Commemorate ("We commemorate Independence Day every August"), Auspicious ("Diwali is considered an auspicious occasion"), Procession ("A colorful procession moved through the streets"), Deity ("Each region worships a different deity"), Folklore ("Indian folklore is rich with stories and legends"), Pilgrimage ("Millions make a pilgrimage to Varanasi each year"), Mosaic ("India is a beautiful cultural mosaic"), Reverence ("We light incense with great reverence"). Write each in your own sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Sequence Words - First, Next, Then, Finally', description: 'When describing rituals and celebrations, sequence words keep your speech organized. Practice this structure: "First, we clean the entire house. Next, we decorate with rangoli. Then, we light diyas in every room. After that, the whole family gathers for puja. Finally, we share sweets with all our neighbors." Now write 6 sentences describing how YOUR family prepares for a festival - using first, next, then, after that, finally.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Be a Cultural Ambassador', description: 'Record yourself for 1 minute explaining one Indian festival to an imaginary foreign friend. Make it exciting! Use sensory language: what you see, hear, smell, taste, and feel during this festival. End with a personal memory. This exact skill is tested in IELTS speaking and job interviews.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 24,
    title: 'News & Current Events',
    description: 'Day 24: People who can discuss current events in English are taken seriously everywhere - in interviews, offices, and social gatherings. Today you will learn to read, understand, and discuss news in English confidently.',
    tasks: [
      { type: 'speaking', title: 'Share a News Story You Heard Recently', description: 'Speak for 2 minutes about any news topic you have seen or heard this week. It can be local, national, or international. Structure: What happened? Where? When? Who was involved? What do YOU think about it? Use: "According to the news...", "I recently read that...", "In my opinion, this is important because..." Even if your English is not perfect, having an opinion matters more.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: BBC or CNN English News', description: 'Search YouTube for "BBC News English today" or "CNN 10 latest" and watch a 5-minute bulletin. Write: 3 news stories you understood, 3 new words you heard, and 1 story you want to discuss. Start with CNN 10 if BBC feels too fast - it is made for students and is spoken more clearly.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This News Report Style Paragraph Aloud', description: 'Read in a clear, serious news anchor voice: "New Delhi, Monday: India has crossed a significant milestone in its digital payments journey, with UPI transactions exceeding 10 billion per month for the first time. The National Payments Corporation of India reported that small businesses, street vendors, and rural consumers are driving this growth. Experts say this transformation is making India one of the most advanced digital economies in the world. The government has announced plans to expand the UPI framework to 20 more countries by 2026." Read it twice - imagine you are on national television.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'News & Media - 10 Words', description: 'Learn: Correspondent ("Our correspondent in Mumbai reports that..."), Editorial ("The newspaper published a strong editorial on pollution"), Verified ("Always check verified sources before sharing news"), Perspective ("Different newspapers give different perspectives"), Allegations ("The minister denied all allegations"), Bilateral ("India signed a bilateral trade agreement with UAE"), Amendment ("Parliament passed an amendment to the law"), Controversy ("The policy change created major controversy"), Transparent ("The government promised a transparent investigation"), Milestone ("India reached a historic milestone in space exploration"). Write each in a news-style sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Reported Speech - How News is Written', description: 'News always uses reported speech. Direct: The Prime Minister said, "We will build 1 million homes." Reported: The Prime Minister said that they would build 1 million homes. Notice: "will" becomes "would", "we" becomes "they". Practice converting these: 1) "I am confident about the economy." (The minister said...) 2) "We have found a solution." (Scientists announced...) 3) "This law will help farmers." (The government claimed...) Write 3 of your own reported speech sentences from real news.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Be a News Anchor for 1 Minute', description: 'Record yourself presenting two news stories like a TV news anchor. Sit up straight, speak clearly, use a professional tone. Start: "Good evening. I am [your name] and here are tonight\'s top stories..." Use the structure: headline + brief details + your closing line. Watching yourself back is one of the fastest ways to improve.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 25,
    title: 'Movies & Music',
    description: 'Day 25: Nearly halfway there! Movies and music are the most enjoyable ways to learn English - and today you will use them actively. The best English learners in the world use entertainment as their classroom. Let\'s do the same.',
    tasks: [
      { type: 'speaking', title: 'Review Your Favorite Movie or Song', description: 'Speak for 2 minutes reviewing your favorite English movie OR an English song you like. Cover: Title, genre, what it is about, why you love it, your favorite scene or lyric, and who you would recommend it to. Use: "The plot is about...", "What makes it special is...", "The scene that moved me most was...", "I would highly recommend this to anyone who..."', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Listen to an English Song and Study the Lyrics', description: 'Pick any English song you enjoy. Search "[song name] lyrics" on Google. Listen to it once just enjoying it. Then listen again reading the lyrics. Write: 5 new words or phrases you found, and 2 lines you found beautiful or interesting. Songs are excellent for learning natural rhythm and emotion in English.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Movie Review Aloud', description: 'Read clearly: "The Shawshank Redemption is not just a prison movie - it is a meditation on hope, friendship, and the unconquerable human spirit. Andy Dufresne, wrongly convicted of murder, refuses to let the prison system destroy his soul. Over nearly two decades, he quietly builds a secret plan while becoming the most valuable inmate in Shawshank. The performances are extraordinary, the story is gripping, and the ending is one of the most satisfying in cinema history. If you have not seen it, stop reading this and watch it tonight." Read it twice with enthusiasm.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Movies & Music - 10 Words', description: 'Learn: Compelling ("The storyline was absolutely compelling"), Portrayal ("Her portrayal of grief was deeply moving"), Cinematography ("The cinematography of this film is stunning"), Dialogue ("The dialogue felt natural and real"), Soundtrack ("The soundtrack gave me goosebumps"), Plot twist ("Nobody saw that plot twist coming"), Critically acclaimed ("This album was critically acclaimed worldwide"), Lyrics ("The lyrics speak directly to my heart"), Genre ("I prefer the thriller genre"), Debut ("His debut album changed music forever"). Write each in a sentence about a real movie or song.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Opinion Phrases - Expressing Views About Entertainment', description: 'In English we use specific phrases to give opinions politely: Strong positive: "I absolutely loved it because...", "It was outstanding - especially..." Mild positive: "It was quite good, although...", "I enjoyed it overall, but..." Negative: "Personally, I did not find it very convincing because...", "I was a bit disappointed with..." Write 3 opinion sentences about a movie and 3 about a song using these structures. Avoid just saying "It was good" or "It was bad."', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Act Out a Famous Movie Dialogue', description: 'Record yourself acting out a famous movie line or scene in English for 1 minute. You can do both characters. Try lines from movies like The Lion King, Spider-Man, or 3 Idiots English version. Really commit to the performance - use different voices, emotions, and energy. This is the most fun confidence exercise in the whole 60 days!', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 26,
    title: 'Cooking & Recipes',
    description: 'Day 26: Food connects people across the world. When you can describe how to cook your mother\'s dal or your grandmother\'s biryani in English, you are sharing something truly special. Today you will master cooking vocabulary and instruction-giving.',
    tasks: [
      { type: 'speaking', title: 'Explain How to Cook Your Favorite Dish', description: 'Speak for 2 minutes giving step-by-step instructions for making your favorite Indian dish. Use cooking verbs: "First, heat oil in a pan...", "Add the onions and saute until golden...", "Then pour in the tomatoes and cook for 5 minutes...", "Season with salt, turmeric, and chilli powder...", "Finally, garnish with fresh coriander and serve hot." Make us hungry!', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Simple English Cooking Tutorial', description: 'Search YouTube for "easy recipe English tutorial for beginners" and watch a 5-minute cooking video. Write down: 5 cooking verbs used (chop, stir, simmer...), 3 measurements mentioned (a teaspoon, half a cup...), and 2 cooking tips given. English cooking videos are excellent because they use clear, slow, instructional English.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Recipe Aloud', description: 'Read clearly like a cooking show host: "Masala Chai - The Perfect Cup. You will need: 1 cup water, 1 cup milk, 2 teaspoons tea leaves, 1 teaspoon sugar, 2 cardamom pods, and a small piece of ginger. First, crush the cardamom and ginger. Bring the water to a boil in a small pan. Add the crushed spices and let them simmer for 2 minutes - you will smell the most wonderful aroma. Add the tea leaves and boil for one more minute. Pour in the milk, add sugar, and bring to a full boil. Strain into cups and serve immediately. The perfect chai is hot, fragrant, and made with love." Read it twice.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Cooking - 10 Essential Words', description: 'Learn: Saute ("Saute the onions in butter until soft"), Simmer ("Let the curry simmer for 20 minutes"), Marinate ("Marinate the chicken overnight for best flavor"), Garnish ("Garnish the soup with fresh herbs"), Texture ("I love the crunchy texture of this snack"), Aroma ("The aroma of fresh bread fills the kitchen"), Blend ("Blend all ingredients until smooth"), Caramelize ("Caramelize the onions slowly over low heat"), Portion ("Each portion should be about 200 grams"), Wholesome ("This is a simple, wholesome meal"). Write each in a cooking sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Imperative Verbs in Cooking Instructions', description: 'Recipes always use imperative - the verb comes first with no subject. This is the same as directions from Day 13. Examples: "Boil the water." "Add two cups of rice." "Stir continuously." "Do not let it burn." "Cover with a lid and wait 10 minutes." "Remove from heat immediately." Now write a mini recipe for ANY simple dish using at least 8 imperative sentences. Could be chai, Maggi, or anda bhurji!', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Host Your Own Cooking Show', description: 'Record yourself for 1 minute as a cooking show host teaching your signature dish. Be warm, enthusiastic, and clear. Look at the camera (your phone), use hand gestures to show measurements, and make it entertaining. Start: "Welcome back to my kitchen! Today I am going to show you how to make the most delicious..." This is genuinely one of the best speaking exercises for fluency.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 27,
    title: 'Fashion & Clothing',
    description: 'Day 27: Fashion is everywhere - job interviews, social media, shopping. Describing clothes and personal style is a very common English conversation topic. Today you will learn to describe what you wear, what you like, and why fashion matters.',
    tasks: [
      { type: 'speaking', title: 'Describe Your Personal Style', description: 'Speak for 2 minutes about your personal style and what you are wearing today. Go beyond just colors: "I would describe my style as casual but put-together...", "Today I am wearing...", "I usually prefer... because...", "For important occasions I tend to wear...", "The one item I could not live without in my wardrobe is..." Fashion language builds descriptive vocabulary faster than almost anything else.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Fashion English Vocabulary', description: 'Search YouTube for "fashion vocabulary in English" and watch a 5-minute video. Write 5 clothing-related adjectives you did not know before (structured, flowy, tailored, minimalist, statement). Notice how fashion presenters describe clothes using sensory and visual language.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Fashion Description Aloud', description: 'Read with style: "Indian fashion is a stunning blend of ancient tradition and modern creativity. A simple cotton kurta paired with slim jeans has become the go-to everyday look for millions of young Indians. Sarees, sherwanis, and lehengas remain the gold standard for celebrations - their intricate embroidery and vibrant colors tell stories of regional identity and family heritage. Meanwhile, Indian designers are dressing global celebrities on red carpets worldwide. Whether you wear a 200-rupee t-shirt or a 20,000-rupee lehenga, the way you carry yourself matters more than the label." Read it twice.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Fashion & Style - 10 Words', description: 'Learn: Tailored ("He wore a perfectly tailored suit"), Versatile ("A white shirt is the most versatile clothing item"), Accessory ("The right accessory can transform any outfit"), Minimalist ("Her minimalist style uses only black and white"), Vibrant ("She loves vibrant colors like orange and yellow"), Embroidery ("The saree had beautiful hand embroidery"), Contemporary ("The designer blends traditional and contemporary styles"), Wardrobe ("I need to update my wardrobe for the new job"), Silhouette ("The flowing silhouette of the dress was elegant"), Texture ("I love mixing different textures in one outfit"). Write each in your own sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Adjective Combinations for Describing Clothes', description: 'Fashion descriptions use multiple adjectives in order: Opinion + Size + Color + Material + Type of clothing. Examples: "a beautiful long blue silk saree", "a smart fitted white cotton shirt", "a gorgeous oversized dark green woolen sweater". Practice: Write 5 complete clothing descriptions using at least 3 adjectives each. Think about items in your own wardrobe.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Your Personal Fashion Review', description: 'Record yourself for 1 minute reviewing your outfit today OR describing your dream outfit for a special occasion. Include: colors, materials, style, why you chose it, and how it makes you feel. End with: "Overall, I would rate this look..." Fashion commentary is excellent practice for using descriptive, confident English.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 28,
    title: 'Home & Furniture',
    description: 'Day 28: Four weeks complete - you are extraordinary! Describing spaces, rooms, and homes is a very practical English skill. You use it when meeting new people, house hunting, or simply making conversation. Today every room in your home becomes an English classroom.',
    tasks: [
      { type: 'speaking', title: 'Give a Tour of Your Home', description: 'Speak for 2 minutes describing your home or room as if showing it to a new friend virtually. Use location words: "As you enter, you will see...", "On the left is...", "The bedroom is at the end of the corridor...", "From the window you can see...", "My favorite corner is... because..." Describe furniture, colors, and what makes your space special or unique to your family.', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: English Home Tour Videos', description: 'Search YouTube for "home tour in English" or "describe your house in English" and watch one video. Write down: 5 location words used (opposite, beside, adjacent, in the corner, facing), and 3 phrases to describe a room positively ("cozy and warm", "bright and airy", "compact but functional"). These are used in real estate, travel, and social conversations.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Home Description Aloud', description: 'Read with warmth: "My grandmother\'s house in the village is the most comforting place I have ever known. The moment you step through the heavy wooden door, the smell of incense and fresh flowers greets you. The main room has a low ceiling with beautiful clay walls painted white. A large brass diya always burns near the small temple in the corner. The kitchen is tiny but produces the most extraordinary food. At night, we sleep on the rooftop under a sky full of stars, listening to crickets and distant temple bells. No five-star hotel in the world could ever match it." Read it twice with love.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Home & Space - 10 Words', description: 'Learn: Adjacent ("The bathroom is adjacent to the bedroom"), Cozy ("This small room is surprisingly cozy"), Ventilated ("All rooms are well ventilated"), Spacious ("The living room is very spacious"), Cluttered ("My desk is always cluttered with books"), Renovate ("We plan to renovate the kitchen next year"), Partition ("A glass partition separates the office areas"), Balcony ("I have my morning tea on the balcony"), Terrace ("We celebrate festivals on the open terrace"), Compact ("It is a compact flat but very efficiently designed"). Write each in a sentence about your home.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'There Is / There Are + Prepositions of Place', description: 'Describing rooms uses "there is/are" with location words. There is (singular): "There is a large window facing east." There are (plural): "There are three chairs around the dining table." Location words: in, on, under, above, beside, opposite, between, behind, in front of. Write 8 sentences describing YOUR room using there is/there are + a location word. Example: "There is a photo of my family on the wall above my desk."', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Describe Your Dream Home', description: 'Record yourself for 1 minute describing your dream home in vivid detail. Where is it located? What does it look like from outside? Describe 3 rooms in detail. What is the most special feature? Use present tense as if it already exists: "My dream home is located in..." This exercise combines creativity, vocabulary, and fluency.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 29,
    title: 'Animals & Pets',
    description: 'Day 29: One day before a major milestone! Animals are a universal topic - everyone has a childhood memory, a pet story, or a wildlife encounter. Today you will use animal topics to practice descriptive English, modal verbs, and storytelling.',
    tasks: [
      { type: 'speaking', title: 'Talk About an Animal That Fascinates You', description: 'Speak for 2 minutes about your favorite animal or pet. Cover: What animal is it? What does it look like? Where does it live? What is special or surprising about it? Do you have a personal story involving this animal? Use: "What fascinates me about... is that...", "Most people do not know that...", "I once had an experience where..."', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: A BBC Earth Animal Documentary Clip', description: 'Search YouTube for "BBC Earth amazing animal moments" and watch a 5-minute clip. Notice the narrator\'s language - the descriptive adjectives, the dramatic pauses, the way they build suspense. Write 3 sentences from the video that you found particularly powerful or descriptive. The BBC Earth narrator is one of the best models for clear, beautiful English.', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Animal Paragraph Aloud Like a Documentary', description: 'Use a calm, dramatic voice: "The Bengal tiger is one of the most magnificent creatures on earth. Weighing up to 300 kilograms and measuring nearly 3 meters from nose to tail, it is the largest wild cat in the world. Its striking orange coat patterned with black stripes is unique to each individual - like a human fingerprint. The tiger hunts alone, using extraordinary patience and stealth. It can remain perfectly still for hours, watching its prey with amber eyes that miss nothing. Yet despite its power, fewer than 3,000 Bengal tigers remain in the wild today. Every one of them is irreplaceable." Read it twice - louder and more dramatic each time.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Animals & Nature - 10 Words', description: 'Learn: Predator ("The lion is the apex predator of the savannah"), Camouflage ("The chameleon uses camouflage to hide from enemies"), Nocturnal ("Owls are nocturnal - they hunt at night"), Hibernate ("Bears hibernate through the entire winter"), Domesticated ("Dogs were domesticated thousands of years ago"), Instinct ("A mother\'s protective instinct is incredibly powerful"), Endangered ("The snow leopard is critically endangered"), Migrate ("Birds migrate thousands of miles every season"), Omnivore ("Bears are omnivores - they eat both plants and meat"), Territory ("Lions fiercely defend their territory"). Write each in your own sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Can / Could / Might - Animal Abilities and Possibilities', description: 'CAN - certain ability: "A cheetah can run at 120 km/h." "Elephants can remember routes for 50 years." COULD - past ability: "When young, the eagle could fly for 8 hours without rest." MIGHT - possibility: "That noise might be a wild boar." "The snake you saw might have been harmless." Write 3 sentences with can, 2 with could, and 2 with might about animals. Use real animal facts if possible.', xp: 15, duration: 10 },
      { type: 'confidence', title: 'Be a Wildlife Documentary Narrator', description: 'Record yourself for 1 minute narrating a nature documentary about any animal - real or imaginary. Use a calm, serious, dramatic voice. Describe the animal, its habitat, its behavior, and the challenge it faces. Start: "Deep in the forests of central India, a young tiger cub takes its first steps into the world..." Channel your inner David Attenborough!', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
  {
    dayNumber: 30,
    title: 'Science & Discovery',
    description: 'Day 30: HALFWAY THERE! 30 days of consistent English practice. You are stronger, smarter, and more confident than Day 1. Today we celebrate with one of the most exciting topics - science and discovery. India has a great scientific tradition and today you will speak about it proudly.',
    tasks: [
      { type: 'speaking', title: 'Talk About a Scientific Discovery That Amazes You', description: 'Speak for 2 minutes about a scientific achievement or discovery that you find incredible. It could be Chandrayaan, the COVID vaccine, the internet, or any invention. Cover: What is it? How did it happen? Why does it matter? How has it changed the world or your life? Use: "What amazes me is that...", "Before this discovery, people used to...", "The impact of this on everyday life is..."', xp: 20, duration: 2, hasTimer: true, hasRecording: true },
      { type: 'listening', title: 'Watch: Science Explained Simply in English', description: 'Search YouTube for "Kurzgesagt" channel or "science explained English" and watch any 5-minute video. These videos explain complex science simply and beautifully. Write 3 facts you learned and 3 new vocabulary words. Notice how they use passive voice constantly: "was discovered", "has been proven", "is believed to be".', xp: 15, duration: 5 },
      { type: 'reading', title: 'Read This Science Paragraph Aloud', description: 'Read with awe and wonder: "On August 23, 2023, India made history. The Chandrayaan-3 spacecraft successfully landed on the south pole of the Moon - a region no country had ever reached before. India became only the fourth nation to land on the Moon, and the first to reach its most mysterious region. Scientists believe the lunar south pole contains water ice - a discovery that could one day support human life in space. For a country where millions are still learning to read, landing a spacecraft on the Moon represents something extraordinary - the proof that human brilliance has no limit and no border." Read it twice with national pride.', xp: 15, duration: 5, hasTimer: true },
      { type: 'vocabulary', title: 'Science & Discovery - 10 Words', description: 'Learn: Hypothesis ("Scientists formed a hypothesis and tested it"), Phenomenon ("The Northern Lights are a natural phenomenon"), Innovation ("ISRO is known for cost-effective space innovation"), Atom ("Everything in the universe is made of atoms"), Gravity ("Newton discovered the concept of gravity"), Evolution ("Darwin\'s theory of evolution changed biology forever"), Prototype ("Engineers built a prototype to test the design"), Orbit ("The Moon orbits the Earth every 27 days"), Chromosome ("Chromosomes carry our genetic information"), Expedition ("The research expedition reached Antarctica last month"). Write each in your own sentence.', xp: 20, duration: 10 },
      { type: 'grammar', title: 'Passive Voice - How Science is Written', description: 'Science and news always use passive voice. Active: "Newton discovered gravity." Passive: "Gravity was discovered by Newton." More examples: "The vaccine was developed in record time." "Chandrayaan-3 was launched in July 2023." "The experiment has been conducted three times." "Carbon dioxide is produced when fuel is burned." Rule: was/were + past participle for simple past passive. Convert these to passive: 1) "Scientists found water on Mars." 2) "India launched a satellite last year." 3) "Doctors use this medicine worldwide." Write 3 of your own passive sentences about science.', xp: 15, duration: 10 },
      { type: 'confidence', title: '30-Day Reflection + Science Speech', description: 'Record yourself for 1.5 minutes. First 30 seconds: reflect on your 30-day journey. What has improved? What surprised you? Second minute: give a short speech on why science matters for India\'s future. This combines your personal growth with academic English. You have come so far - let your recording prove it.', xp: 25, duration: 3, hasTimer: true, hasRecording: true },
    ],
  },
];

const patch = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected');
  for (const d of updates) {
    const totalXP = d.tasks.reduce((s, t) => s + t.xp, 0);
    await Day.updateOne(
      { dayNumber: d.dayNumber },
      { $set: { description: d.description, tasks: d.tasks, totalXP } }
    );
    console.log(`Updated Day ${d.dayNumber}`);
  }
  console.log('Done!');
  await mongoose.connection.close();
  process.exit(0);
};

patch().catch((e) => { console.error(e); process.exit(1); });
