require('dotenv').config();
const mongoose = require('mongoose');
const DailyChallenge = require('../models/DailyChallenge');

const challenges = [
  { question: 'She ___ to school every day.', options: ['go', 'goes', 'going', 'gone'], correctIndex: 1, explanation: 'Third person singular (she/he/it) takes -s/es in Present Simple.', hindiExplanation: 'She/He/It ke saath verb mein -s/-es lagate hain.', category: 'grammar', difficulty: 'beginner' },
  { question: 'I ___ watching TV when she called.', options: ['was', 'were', 'am', 'is'], correctIndex: 0, explanation: '"I" uses "was" in past continuous.', hindiExplanation: '"I" ke saath Past Continuous mein "was" aata hai.', category: 'tense', difficulty: 'beginner' },
  { question: 'What is the meaning of "Eloquent"?', options: ['Rude', 'Fluent and persuasive', 'Shy', 'Angry'], correctIndex: 1, explanation: 'Eloquent means well-spoken and persuasive.', hindiExplanation: 'Eloquent ka matlab hai prabhavshali tarike se bolna.', category: 'vocabulary', difficulty: 'intermediate' },
  { question: 'The book is ___ the table.', options: ['in', 'on', 'at', 'by'], correctIndex: 1, explanation: '"On" is used for surfaces.', hindiExplanation: 'Kisi cheez ki upar wali jagah ke liye "on" use karte hain.', category: 'preposition', difficulty: 'beginner' },
  { question: 'She has ___ her homework.', options: ['finish', 'finished', 'finishing', 'finishes'], correctIndex: 1, explanation: 'Present Perfect: have/has + past participle.', hindiExplanation: 'Present Perfect mein have/has ke baad verb ki 3rd form aati hai.', category: 'tense', difficulty: 'beginner' },
  { question: 'Which sentence is correct?', options: ['He don\'t like tea.', 'He doesn\'t likes tea.', 'He doesn\'t like tea.', 'He not like tea.'], correctIndex: 2, explanation: 'With "he", use "doesn\'t" and base verb without -s.', hindiExplanation: 'He/She/It ke saath negative mein "doesn\'t" + base verb aata hai.', category: 'grammar', difficulty: 'beginner' },
  { question: '"Break a leg" means:', options: ['Get injured', 'Good luck', 'Run fast', 'Be careful'], correctIndex: 1, explanation: '"Break a leg" is an idiom meaning good luck.', hindiExplanation: '"Break a leg" ek idiom hai jiska matlab hai "best of luck".', category: 'idiom', difficulty: 'intermediate' },
  { question: 'I ___ to Delhi next week.', options: ['go', 'went', 'will go', 'was going'], correctIndex: 2, explanation: 'Future Simple: will + base verb for future plans.', hindiExplanation: 'Future ki baat karne ke liye "will + verb" use karte hain.', category: 'tense', difficulty: 'beginner' },
  { question: 'What is the plural of "child"?', options: ['childs', 'childes', 'children', 'childrens'], correctIndex: 2, explanation: '"Child" is an irregular noun, plural is "children".', hindiExplanation: '"Child" ki plural "children" hoti hai — ye irregular hai.', category: 'grammar', difficulty: 'beginner' },
  { question: '___ you help me please?', options: ['Can', 'Could', 'Both are correct', 'Neither'], correctIndex: 2, explanation: 'Both "Can" and "Could" work for polite requests.', hindiExplanation: 'Vinmra nivedan ke liye "can" aur "could" dono sahi hain.', category: 'grammar', difficulty: 'beginner' },
  { question: '"Meticulous" means:', options: ['Careless', 'Very careful and precise', 'Loud', 'Lazy'], correctIndex: 1, explanation: 'Meticulous means showing great attention to detail.', hindiExplanation: 'Meticulous ka matlab hai baar baar dhyan se kaam karna.', category: 'vocabulary', difficulty: 'intermediate' },
  { question: 'If I ___ rich, I would travel the world.', options: ['am', 'was', 'were', 'be'], correctIndex: 2, explanation: 'Second conditional: If + were (for all subjects) + would.', hindiExplanation: 'Kalpana ki baat mein "If I were" use karte hain.', category: 'tense', difficulty: 'intermediate' },
  { question: 'The meeting is ___ Monday ___ 10 AM.', options: ['on, in', 'at, on', 'on, at', 'in, at'], correctIndex: 2, explanation: '"On" for days, "at" for specific times.', hindiExplanation: 'Dino ke liye "on", samay ke liye "at" use karte hain.', category: 'preposition', difficulty: 'beginner' },
  { question: 'She is ___ than her sister.', options: ['tall', 'more tall', 'taller', 'tallest'], correctIndex: 2, explanation: 'Comparative of short adjectives: add -er.', hindiExplanation: 'Chhoti adjectives ki comparative mein -er lagate hain.', category: 'grammar', difficulty: 'beginner' },
  { question: '"Hit the nail on the head" means:', options: ['Do carpentry', 'Be exactly right', 'Work hard', 'Make a mistake'], correctIndex: 1, explanation: 'This idiom means to be exactly correct about something.', hindiExplanation: 'Ye idiom matlab hai bilkul sahi baat kehna.', category: 'idiom', difficulty: 'intermediate' },
  { question: 'The letter ___ written by her.', options: ['is', 'was', 'were', 'be'], correctIndex: 1, explanation: 'Passive voice in past: was + past participle.', hindiExplanation: 'Past passive mein "was/were + verb ki 3rd form" use karte hain.', category: 'grammar', difficulty: 'intermediate' },
  { question: '"Pragmatic" means:', options: ['Impractical', 'Dealing practically with things', 'Emotional', 'Theoretical'], correctIndex: 1, explanation: 'Pragmatic means taking a practical, realistic approach.', hindiExplanation: 'Pragmatic ka matlab hai vyavharik tarike se sochna.', category: 'vocabulary', difficulty: 'intermediate' },
  { question: 'They ___ playing cricket since morning.', options: ['are', 'were', 'have been', 'had'], correctIndex: 2, explanation: 'Present Perfect Continuous: have been + verb-ing for ongoing action.', hindiExplanation: 'Subah se abhi tak ki ongoing activity ke liye "have been + ing".', category: 'tense', difficulty: 'intermediate' },
  { question: 'I need ___ umbrella today.', options: ['a', 'an', 'the', 'no article needed'], correctIndex: 1, explanation: '"An" before vowel sounds (umbrella starts with vowel sound U).', hindiExplanation: 'Vowel sound se shuru hone wale shabdon se pehle "an" lagate hain.', category: 'grammar', difficulty: 'beginner' },
  { question: 'Which is correct?', options: ['She said that she is tired.', 'She said that she was tired.', 'She said that she were tired.', 'She said that she be tired.'], correctIndex: 1, explanation: 'Reported speech: present tense shifts to past tense.', hindiExplanation: 'Reported speech mein verb ek tense peeche shift ho jaati hai.', category: 'grammar', difficulty: 'intermediate' },
  { question: '"Resilient" means:', options: ['Weak', 'Stubborn', 'Able to recover quickly', 'Sensitive'], correctIndex: 2, explanation: 'Resilient means able to bounce back from difficulties.', hindiExplanation: 'Resilient ka matlab hai mushkilon se jaldi ubhar jaana.', category: 'vocabulary', difficulty: 'advanced' },
  { question: 'I enjoy ___ music.', options: ['to listen', 'listen', 'listening', 'listened'], correctIndex: 2, explanation: '"Enjoy" is always followed by a gerund (verb+ing).', hindiExplanation: '"Enjoy" ke baad hamesha gerund (verb+ing) aata hai.', category: 'grammar', difficulty: 'intermediate' },
  { question: 'By tomorrow, I ___ the project.', options: ['finish', 'will finish', 'will have finished', 'finishing'], correctIndex: 2, explanation: 'Future Perfect: will have + past participle for completion before future time.', hindiExplanation: 'Future mein kisi time se pehle poori hone wali action ke liye Future Perfect.', category: 'tense', difficulty: 'advanced' },
  { question: '"Cost an arm and a leg" means:', options: ['Be cheap', 'Be very expensive', 'Work hard', 'Travel far'], correctIndex: 1, explanation: 'This idiom means something is very expensive.', hindiExplanation: 'Is idiom ka matlab hai bahut zyada mahanga hona.', category: 'idiom', difficulty: 'intermediate' },
  { question: 'He works ___ Delhi.', options: ['in', 'at', 'on', 'to'], correctIndex: 0, explanation: '"In" is used for cities and large places.', hindiExplanation: 'Shahar aur bade jagahon ke liye "in" use karte hain.', category: 'preposition', difficulty: 'beginner' },
  { question: '"Ambiguous" means:', options: ['Clear', 'Having more than one meaning', 'Simple', 'Direct'], correctIndex: 1, explanation: 'Ambiguous means unclear or having multiple interpretations.', hindiExplanation: 'Ambiguous ka matlab hai jiska ek se zyada matlab ho sakta hai.', category: 'vocabulary', difficulty: 'advanced' },
  { question: 'Neither he ___ she was present.', options: ['or', 'nor', 'and', 'but'], correctIndex: 1, explanation: '"Neither...nor" is the correct correlative conjunction pair.', hindiExplanation: '"Neither" ke saath hamesha "nor" aata hai.', category: 'grammar', difficulty: 'intermediate' },
  { question: 'The man ___ helped us was kind.', options: ['which', 'what', 'who', 'whose'], correctIndex: 2, explanation: '"Who" is used for people in relative clauses.', hindiExplanation: 'Logon ke bare mein relative clause mein "who" use karte hain.', category: 'grammar', difficulty: 'beginner' },
  { question: 'She speaks English ___.', options: ['fluent', 'fluently', 'more fluent', 'fluents'], correctIndex: 1, explanation: 'Adverbs (fluently) modify verbs, not nouns.', hindiExplanation: 'Verb ko modify karne ke liye adverb (fluently) use karte hain.', category: 'grammar', difficulty: 'beginner' },
  { question: 'If you ___ hard, you will succeed.', options: ['work', 'worked', 'will work', 'works'], correctIndex: 0, explanation: 'First conditional: If + present simple, will + base verb.', hindiExplanation: 'First conditional mein "if" ke baad present simple aata hai.', category: 'tense', difficulty: 'intermediate' },
];

async function seedChallenges() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected ✅');
  await DailyChallenge.deleteMany({});
  await DailyChallenge.insertMany(challenges);
  console.log(`✅ Seeded ${challenges.length} daily challenge questions`);
  process.exit(0);
}

seedChallenges().catch((err) => { console.error(err); process.exit(1); });
