// 60 days × 5 words each — fetched live from Free Dictionary API
// Words are carefully chosen by difficulty and topic matching the 60-day curriculum

const DAILY_WORDS = {
  1:  ['introduce', 'greet', 'fluent', 'practice', 'confident'],
  2:  ['farewell', 'polite', 'formal', 'casual', 'respond'],
  3:  ['vocabulary', 'meaning', 'definition', 'synonym', 'context'],
  4:  ['sentence', 'subject', 'object', 'verb', 'simple'],
  5:  ['pronunciation', 'syllable', 'accent', 'phonetic', 'clarity'],
  6:  ['schedule', 'punctual', 'deadline', 'duration', 'precise'],
  7:  ['describe', 'transparent', 'fragile', 'enormous', 'glossy'],
  8:  ['sibling', 'ancestor', 'guardian', 'relative', 'spouse'],
  9:  ['cuisine', 'savory', 'appetizer', 'portion', 'tender'],
  10: ['routine', 'commute', 'productive', 'consistent', 'priority'],
  11: ['humid', 'forecast', 'drizzle', 'climate', 'breeze'],
  12: ['discount', 'receipt', 'budget', 'purchase', 'bargain'],
  13: ['destination', 'journey', 'passenger', 'luggage', 'explore'],
  14: ['colleague', 'deadline', 'promotion', 'presentation', 'client'],
  15: ['symptom', 'nutrition', 'recovery', 'treatment', 'fitness'],
  16: ['frustrated', 'grateful', 'embarrassed', 'motivated', 'anxious'],
  17: ['passion', 'creative', 'collection', 'adventure', 'leisure'],
  18: ['software', 'download', 'network', 'browser', 'artificial'],
  19: ['pollution', 'ecosystem', 'recycle', 'conservation', 'habitat'],
  20: ['tournament', 'athlete', 'victory', 'strategy', 'championship'],
  21: ['scholarship', 'curriculum', 'internship', 'discipline', 'lecture'],
  22: ['trustworthy', 'companion', 'loyalty', 'socialize', 'bond'],
  23: ['tradition', 'ceremony', 'heritage', 'ritual', 'community'],
  24: ['headline', 'journalist', 'economy', 'policy', 'debate'],
  25: ['soundtrack', 'performance', 'genre', 'audience', 'melody'],
  26: ['ingredient', 'recipe', 'flavor', 'simmer', 'garnish'],
  27: ['elegant', 'casual', 'trendy', 'fabric', 'accessory'],
  28: ['interior', 'appliance', 'curtain', 'mattress', 'balcony'],
  29: ['predator', 'habitat', 'domestic', 'species', 'wildlife'],
  30: ['experiment', 'innovation', 'laboratory', 'theory', 'discovery'],
  31: ['revenue', 'negotiation', 'investment', 'strategy', 'leadership'],
  32: ['qualification', 'responsibility', 'adaptability', 'achievement', 'opportunity'],
  33: ['attachment', 'recipient', 'inquiry', 'confirmation', 'compose'],
  34: ['voicemail', 'transfer', 'connection', 'receiver', 'dial'],
  35: ['demonstrate', 'conclusion', 'summary', 'visual', 'audience'],
  36: ['perspective', 'argument', 'evidence', 'counterargument', 'opinion'],
  37: ['narration', 'incident', 'mystery', 'character', 'adventure'],
  38: ['idiom', 'expression', 'phrase', 'figurative', 'colloquial'],
  39: ['phrasal', 'combination', 'particle', 'separable', 'inseparable'],
  40: ['formal', 'informal', 'professional', 'casual', 'appropriate'],
  41: ['analyze', 'infer', 'comprehend', 'passage', 'summarize'],
  42: ['fluency', 'shadowing', 'accent', 'rhythm', 'intonation'],
  43: ['paragraph', 'structure', 'draft', 'edit', 'clarity'],
  44: ['hesitation', 'smooth', 'natural', 'connector', 'expression'],
  45: ['tense', 'clause', 'phrase', 'adverb', 'preposition'],
  46: ['continuous', 'perfect', 'timeline', 'habit', 'experience'],
  47: ['article', 'definite', 'indefinite', 'preposition', 'position'],
  48: ['conjunction', 'moreover', 'consequently', 'furthermore', 'therefore'],
  49: ['reported', 'indirect', 'mention', 'announce', 'suggest'],
  50: ['conditional', 'possibility', 'consequence', 'imagine', 'outcome'],
  51: ['exceptional', 'remarkable', 'significant', 'ambitious', 'determined'],
  52: ['inspire', 'gesture', 'impact', 'persuade', 'communicate'],
  53: ['courage', 'determination', 'boldness', 'resilience', 'motivation'],
  54: ['actually', 'definitely', 'absolutely', 'naturally', 'honestly'],
  55: ['professionalism', 'productivity', 'skillset', 'flexible', 'teamwork'],
  56: ['collaboration', 'interaction', 'participation', 'suggestion', 'perspective'],
  57: ['justify', 'convince', 'reasoning', 'counterpoint', 'conclusion'],
  58: ['revision', 'improvement', 'reflection', 'milestone', 'progress'],
  59: ['consistency', 'excellence', 'dedication', 'persistence', 'growth'],
  60: ['mastery', 'champion', 'fluency', 'achievement', 'success'],
};

export const getDayWords = (dayNumber) => {
  const day = Math.min(Math.max(dayNumber, 1), 60);
  return DAILY_WORDS[day] || DAILY_WORDS[1];
};

export default DAILY_WORDS;
